FROM rust:1-slim AS build

WORKDIR /src
COPY . .
RUN cargo build --release

FROM debian:stable-slim

COPY --from=build /src/target/release/{{ c.package }} /usr/local/bin/app
{%- if c.workers or c.consumers %}
COPY --from=build /src/target/release/workers /usr/local/bin/workers
{%- endif %}

EXPOSE 8000
CMD ["app"]
