#!/usr/bin/env python3
"""The v0.17 M5 checkpoint's own live proof. Not part of `ciac` itself
-- run by hand (or by CI) to answer the Rollout strategy's go/no-go
question for this one milestone:

    python3 sim/pyrunner/run_vertical_slice.py

Steps: (1) regenerate `examples/sim-vertical-slice.ciac` fresh via the
real `ciac` binary, (2) seed the one classic-handler stub the fixture
needs (a one-time act a human/agent would normally do -- see
`seed_run_reconcile`), (3) `uv sync` the generated project's real
dependencies, (4) run `inner_proof.py` inside that project's own venv,
which drives the real generated code (not a mock) through the exact
effect chain 17UpdatePlan.md's Rollout strategy names, and (5) compare
the reported timings against this document's stated 1.0s p95 / 500ms
budgets and report pass/fail plainly.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PROJECT_DIR = REPO_ROOT / "target" / "sim-m5-checkpoint" / "sim-vertical-slice-py"
PYRUNNER_DIR = Path(__file__).resolve().parent

VERTICAL_SLICE_P95_BUDGET_MS = 1000.0
VIRTUAL_WEEK_BUDGET_MS = 500.0

RUN_RECONCILE_SEED = '''"""Handler for the `RunReconcile` pipeline step. Generated by CIaC.

This file is yours: the compiler wires `RunReconcile` into its
pipelines, and you implement the business logic in `handle`.

Seeded once by the v0.17 M5 checkpoint's runner (`sim/pyrunner/
run_vertical_slice.py`) as a stand-in for what a human or agent would
normally write by hand -- regeneration never overwrites this file (see
`docs/authoring.md`'s seeded-code discipline), so this seed only needs
applying the first time a project is generated at this path.
"""

from typing import Any
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import AuditEntries


class RunReconcile:
    """Business logic for the `RunReconcile` step.

    Capability bindings:
    - db: default
    """

    def __init__(
        self,
        session: AsyncSession | None = None,
    ) -> None:
        self.session = session

    async def handle(self, payload: dict[str, Any]) -> dict[str, Any]:
        import uuid

        self.session.add(AuditEntries(id=str(uuid.uuid4()), note="reconciled"))
        await self.session.commit()
        return payload
'''


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    print(f"+ {' '.join(cmd)}", file=sys.stderr)
    try:
        return subprocess.run(cmd, check=True, **kwargs)
    except subprocess.CalledProcessError as e:
        if e.stdout:
            print(e.stdout, file=sys.stderr)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        raise


def build_project() -> None:
    if PROJECT_DIR.exists():
        shutil.rmtree(PROJECT_DIR)
    PROJECT_DIR.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            "cargo",
            "run",
            "-q",
            "--bin",
            "ciac",
            "--",
            "build",
            "examples/sim-vertical-slice.ciac",
            "--target",
            "python",
            "--out",
            str(PROJECT_DIR),
        ],
        cwd=REPO_ROOT,
    )


def seed_run_reconcile() -> None:
    path = PROJECT_DIR / "app" / "services" / "run_reconcile.py"
    path.write_text(RUN_RECONCILE_SEED)


def uv_sync() -> None:
    run(["uv", "sync"], cwd=PROJECT_DIR)


def run_inner_proof() -> dict:
    import os

    full_env = dict(os.environ)
    full_env["PYTHONPATH"] = os.pathsep.join([str(PYRUNNER_DIR), str(PROJECT_DIR)])
    result = run(
        ["uv", "run", "python", str(PYRUNNER_DIR / "inner_proof.py")],
        cwd=PROJECT_DIR,
        env=full_env,
        capture_output=True,
        text=True,
    )
    print(result.stderr, file=sys.stderr)
    return json.loads(result.stdout)


def main() -> None:
    build_project()
    seed_run_reconcile()
    uv_sync()
    report = run_inner_proof()

    print(json.dumps(report, indent=2))

    vs = report["vertical_slice"]
    vw = report["virtual_week"]
    replay_ok = report["replay_equivalent"]

    checks = {
        "replay_equivalent": replay_ok,
        f"vertical_slice p95 <= {VERTICAL_SLICE_P95_BUDGET_MS}ms": vs["p95_ms"]
        <= VERTICAL_SLICE_P95_BUDGET_MS,
        f"virtual_week elapsed <= {VIRTUAL_WEEK_BUDGET_MS}ms": vw["elapsed_ms"]
        <= VIRTUAL_WEEK_BUDGET_MS,
        "no unmatched failure rules": vs["last_result"]["failure_unmatched"] == [],
        "worker succeeded on third attempt": vs["last_result"]["processed_orders"] == 1,
        "cron job ran exactly once over 24h": vs["last_result"] is not None,
    }

    print("\n=== M5 checkpoint go/no-go ===")
    all_pass = True
    for name, ok in checks.items():
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
        all_pass = all_pass and ok

    print(f"\nDECISION: {'GO' if all_pass else 'NO-GO'}")
    sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
