#!/usr/bin/env python3
"""v0.17 M9's live proof: runs both checked-in scenario files
(`sim/vertical-slice.ciac-sim.json`, `sim/virtual-week.ciac-sim.json`)
through the generic `scenario_runner.ScenarioRunner`, against a freshly
generated `sim-vertical-slice` project -- no hand-written per-step
translation (M5's `inner_proof.py` did that), no mocks, no Docker.

Run: `python3 sim/pyrunner/run_scenario.py`
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PROJECT_DIR = REPO_ROOT / "target" / "sim-m9-checkpoint" / "sim-vertical-slice-py"
PYRUNNER_DIR = Path(__file__).resolve().parent
SCENARIO_PATHS = [
    REPO_ROOT / "sim" / "vertical-slice.ciac-sim.json",
    REPO_ROOT / "sim" / "virtual-week.ciac-sim.json",
]
VERTICAL_SLICE_BUDGET_MS = 1000.0
VIRTUAL_WEEK_BUDGET_MS = 500.0

RUN_RECONCILE_SEED = '''"""Handler for the `RunReconcile` pipeline step. Generated by CIaC.

Seeded once by the v0.17 M9 checkpoint's runner
(`sim/pyrunner/run_scenario.py`), the same seed M5's own
`run_vertical_slice.py` applies -- regeneration never overwrites this
file (see `docs/authoring.md`'s seeded-code discipline).
"""

from typing import Any
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import AuditEntries


class RunReconcile:
    def __init__(self, session: AsyncSession | None = None) -> None:
        self.session = session

    async def handle(self, payload: dict[str, Any]) -> dict[str, Any]:
        import uuid

        self.session.add(AuditEntries(id=str(uuid.uuid4()), note="reconciled"))
        await self.session.commit()
        return payload
'''


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    print(f"+ {' '.join(cmd)}", file=sys.stderr)
    try:
        return subprocess.run(cmd, check=True, **kwargs)
    except subprocess.CalledProcessError as e:
        if e.stdout:
            print(e.stdout, file=sys.stderr)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        raise


def build_project() -> None:
    if PROJECT_DIR.exists():
        shutil.rmtree(PROJECT_DIR)
    PROJECT_DIR.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            "cargo", "run", "-q", "--bin", "ciac", "--",
            "build", "examples/sim-vertical-slice.ciac", "--target", "python", "--out", str(PROJECT_DIR),
        ],
        cwd=REPO_ROOT,
    )
    (PROJECT_DIR / "app" / "services" / "run_reconcile.py").write_text(RUN_RECONCILE_SEED)


def uv_sync() -> None:
    run(["uv", "sync"], cwd=PROJECT_DIR)


def dump_plan_hashes() -> tuple[str, str]:
    result = run(
        [
            "cargo", "run", "-q", "--example", "dump_plan", "-p", "ciac-sim", "--",
            "examples/sim-vertical-slice.ciac", "--hash",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    hashes = json.loads(result.stdout)
    return hashes["source_hash"], hashes["plan_hash"]


def run_inner_proof(scenario_path: Path, extra_args: list[str] | None = None) -> dict:
    full_env = dict(os.environ)
    full_env["PYTHONPATH"] = os.pathsep.join([str(PYRUNNER_DIR), str(PROJECT_DIR)])
    result = run(
        [
            "uv", "run", "python", str(PYRUNNER_DIR / "inner_proof_scenario.py"),
            str(scenario_path), *(extra_args or []),
        ],
        cwd=PROJECT_DIR,
        env=full_env,
        capture_output=True,
        text=True,
    )
    print(result.stderr, file=sys.stderr)
    return json.loads(result.stdout)


def main() -> None:
    build_project()
    uv_sync()
    source_hash, plan_hash = dump_plan_hashes()

    budgets = {
        "v0.17-m5-vertical-slice": VERTICAL_SLICE_BUDGET_MS,
        "v0.17-m5-virtual-week": VIRTUAL_WEEK_BUDGET_MS,
    }
    all_pass = True
    for scenario_path in SCENARIO_PATHS:
        report = run_inner_proof(scenario_path)
        print(json.dumps(report, indent=2))
        budget = budgets.get(report["scenario"])
        within_budget = budget is None or report["elapsed_ms"] <= budget
        ok = report["passed"] and within_budget
        print(
            f"  [{'PASS' if ok else 'FAIL'}] {report['scenario']} "
            f"({report['elapsed_ms']:.2f}ms, budget {budget}ms)"
        )
        all_pass = all_pass and ok

    # Replay: record an artifact for the vertical-slice scenario, then
    # replay it -- both the compatibility check (hashes must match)
    # and the transcript comparison must hold against a real recorded
    # run, not just an in-memory repeat.
    replay_path = PROJECT_DIR / "vertical-slice.replay.json"
    vertical_slice = SCENARIO_PATHS[0]
    record_report = run_inner_proof(
        vertical_slice,
        ["--source-hash", source_hash, "--plan-hash", plan_hash, "--record", str(replay_path)],
    )
    recorded_ok = record_report["passed"] and replay_path.exists()
    print(f"  [{'PASS' if recorded_ok else 'FAIL'}] replay artifact recorded")
    all_pass = all_pass and recorded_ok

    replay_report = run_inner_proof(
        vertical_slice,
        ["--source-hash", source_hash, "--plan-hash", plan_hash, "--replay", str(replay_path)],
    )
    replay_ok = replay_report["passed"]
    print(f"  [{'PASS' if replay_ok else 'FAIL'}] replay matched the recorded transcript")
    all_pass = all_pass and replay_ok

    # A stale plan_hash must be refused, not guessed compatible.
    mismatch_report = run_inner_proof(
        vertical_slice,
        ["--source-hash", source_hash, "--plan-hash", "sha256:stale", "--replay", str(replay_path)],
    )
    mismatch_rejected = not mismatch_report["passed"] and "plan_hash" in (mismatch_report["error"] or "")
    print(f"  [{'PASS' if mismatch_rejected else 'FAIL'}] stale plan_hash is refused, not guessed")
    all_pass = all_pass and mismatch_rejected

    print(f"\nDECISION: {'PASS' if all_pass else 'FAIL'}")
    sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
