"""The Python simulation driver, not generated by `ciac build`.

Originated in v0.17 as the first (and, until 27UpdatePlan.md, only)
full-fidelity target: `FakeDatabase` (insert/update/delete/query/count
by primary key or predicate, schema-aware reference/unique/cascade
checking, atomic `commit_batch`), `FakeBroker` (per-`(subject, group)`
cursors, true fan-out, lost-ack redelivery), `VirtualClock`,
`FakeCache`, `FakeObjectStore`, `FakeEmail`, `FakeSearch`,
`FakeHttpClient` (fixture-driven), `FakeAuth` (claims-lookup, no
crypto), and worker retry/redelivery (`deliver_counting_attempts`).
`auto_driver.py` interprets `ciac_sim::Scenario` JSON directly against
a generated project's own handlers -- the "no generic JSON-scenario
interpreter" gap this docstring once disclosed closed in v0.17 itself;
`run_vertical_slice.py`/`run_domain_orders.py` predate that and remain
as hand-written inner-proof scripts, not the primary driving path.

Constraint metadata (reference existence, `unique`, cascade/restrict)
comes from `ciac_sim::SimPlan`, not from reflecting the generated
project's own SQLAlchemy models: `crates/ciac-sim/examples/dump_plan.rs`
prints `SimPlan` as JSON for a `.ciac` file; `Schema.load` below parses
it. Traced empirically: generated `app/models.py` columns are plain,
constraint-free `Mapped[str]` declarations (`customer_id: Mapped[str]
= mapped_column(Text)`, no `ForeignKey`, no `UniqueConstraint`) -- real
FK/cascade/unique enforcement lives only in migration SQL text and,
canonically, in `SimPlan` itself; reflecting SQLAlchemy metadata would
find nothing there to reflect.

27UpdatePlan.md M9 closed Python's own last disclosed gap: `db.update`
(via `_FakeSession.get()`-then-`setattr`-then-`commit()`, matching
`db_update_tail`'s generated shape exactly) and predicate-filtered
`db.query`/`db.count`/`db.delete_where` (via `_FakeSession.execute()`
and `_compile_predicate`, which interprets the real `select`/
`sql_delete` statement objects `where_chain` builds rather than
re-implementing SQL). See `_FakeSession`'s own docstring below for the
mutation-detection design (snapshot-diff at `.commit()` time, so a
plain read-only `.get()` doesn't manufacture a spurious update).

Disclosed, still out of scope:

- Indexes: `index: true` on a plain scalar field is silently discarded
  by the compiler itself -- there is nothing for a fake to enforce
  that production doesn't already no-op. `SimPlan` does not carry
  index metadata for this reason.
- Constraint-violation-to-409/422 HTTP mapping: domain-orders.ciac's
  own header comment discloses this mapping doesn't exist on the real
  Postgres path either ("`InvalidOrder`/insufficient-funds-style
  failures surface as a raw 500, not a mapped 409/422"). Inventing the
  mapping only in the fake would make the fake strictly more capable
  than production -- so the exception types below are unmapped,
  matching today's real behavior on both targets.
- `on_update` cascade/restrict: no generated code path ever updates a
  primary key (IDs are immutable UUIDs), so there is no real behavior
  to match; `Schema` records the action but nothing triggers it.
- The failure vocabulary stays `error`-action-only, matching
  `FailureEngine`'s own scope: `Delay`/`Timeout`/`Lose`/`Duplicate`/
  `Disconnect` remain parse-but-refuse across every target, an
  explicit 27UpdatePlan.md cut, not a Python-specific gap.
- Multi-service simulation (routing a call across >1 generated
  project's own handlers inside one world): out of scope for this
  arc entirely -- 28UpdatePlan.md's job.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Callable

# Matches `ciac_backend_python::lower::SEARCH_INDEX_NAME` (lower.rs:68)
# and `ciac_sim::world::SEARCH_INDEX_NAME` (Rust) exactly -- every
# generated `search.index`/`search.query` call is hardcoded to this one
# index name, so callers seeding or asserting against `FakeSearch`
# (`auto_driver.py`'s `apply_given`, `scenario_runner.py`'s
# `expect.search_hits`) use it too rather than adding a dimension no
# generated code ever varies.
SEARCH_INDEX_NAME = "documents"


class ReferenceViolation(Exception):
    """A `Reference<T>` field pointed at a row that doesn't exist, or a
    delete was blocked by an `on_delete: restrict` reference. Unmapped
    to any HTTP status -- see the module docstring."""


class UniqueViolation(Exception):
    """A `Reference<T> { unique: true }` field's target already has a
    row. Unmapped to any HTTP status -- see the module docstring."""


class RoutingError(Exception):
    """28UpdatePlan.md M3: a `call_checked` routed call named an
    unregistered `(service, api)`, or exceeded `SimWorld.
    MAX_CALL_DEPTH` -- reported clearly, not silently ignored or left
    to crash as an opaque `RecursionError`. Distinct from `auto_driver.
    py`'s own `RegistryError` (a scenario-level "this driver doesn't
    know how to auto-wire that name" refusal) -- this one is
    world-level, raised by `call_checked` itself regardless of which
    driver built the registry."""


def to_snake_case(name: str) -> str:
    """Matches `ciac_sim::plan::snake_case` (Rust) exactly, which is
    itself documented there as matching `heck::ToSnakeCase` closely
    enough for CIaC's ASCII identifiers -- so a `SimPlan` table name
    ("LineItems") lands on the same string as the generated
    `__tablename__` ("line_items") this fake indexes by."""
    out: list[str] = []
    for i, c in enumerate(name):
        if c.isupper():
            if i != 0:
                out.append("_")
            out.append(c.lower())
        else:
            out.append(c)
    return "".join(out)


def namespaced_table_key(service: str | None, table: str) -> str:
    """28UpdatePlan.md M3: mirrors `ciac_sim::world::SimWorld::
    namespaced_table_key` (Rust, M2) exactly -- `None` (the single-
    service degenerate case, still every project generated before this
    arc and every single-service project generated after it) returns
    `table` unchanged; `Some(service)` returns `f"{service}/{table}"`.
    A free function, not a `FakeDatabase`/`SimWorld` method, so the
    degenerate path is provably a no-op by inspection: nothing about
    `FakeDatabase` itself changes for this milestone, only what key a
    caller chooses to pass it -- exactly Rust's own M2 shape, where
    `namespaced_table_key` composes the key a caller passes to
    `FakeDatabase`'s own unmodified, bare-string-keyed methods."""
    if service is None:
        return table
    return f"{service}/{table}"


@dataclass
class ReferenceColumn:
    """One `Reference<T>` column's constraint metadata, resolved to the
    generated Python attribute name (`<field>_id`) and the target
    table's snake-case name -- both conventions confirmed empirically
    against real generated `app/models.py` output, not assumed."""

    python_attr: str
    target_table_snake: str
    on_delete: str  # "Restrict" | "Cascade"
    unique: bool


@dataclass
class TableSchema:
    references: list[ReferenceColumn] = field(default_factory=list)


class Schema:
    """Parses a `SimPlan` JSON document (see `dump_plan.rs`) into a
    lookup keyed by the generated project's own snake_case table
    names. `Schema.empty()` (no constraints) preserves M5's behavior
    for callers that don't need M6's checking -- `FakeDatabase` without
    a schema is exactly as permissive as it was before this revision.
    """

    def __init__(self, tables: dict[str, TableSchema]) -> None:
        self.tables = tables

    @classmethod
    def empty(cls) -> "Schema":
        return cls({})

    @classmethod
    def from_plan_json(cls, plan: dict[str, Any]) -> "Schema":
        tables: dict[str, TableSchema] = {}
        table_key_to_snake = {
            t["key"]: to_snake_case(t["name"]) for t in plan["tables"]
        }
        for t in plan["tables"]:
            snake = table_key_to_snake[t["key"]]
            schema = TableSchema()
            for col in t["columns"]:
                ty = col["ty"]
                if ty.get("type") == "Reference" and ty.get("target_table"):
                    schema.references.append(
                        ReferenceColumn(
                            python_attr=f"{col['name']}_id",
                            target_table_snake=table_key_to_snake[ty["target_table"]],
                            on_delete=ty["on_delete"],
                            unique=ty["unique"],
                        )
                    )
            tables[snake] = schema
        return cls(tables)

    def references_to(self, table_snake: str) -> list[tuple[str, ReferenceColumn]]:
        """Every `(referencing_table, ReferenceColumn)` pointing at
        `table_snake` -- what a delete of a row in `table_snake` must
        check."""
        return [
            (referencing_table, ref)
            for referencing_table, schema in self.tables.items()
            for ref in schema.references
            if ref.target_table_snake == table_snake
        ]


class FakeDatabase:
    """Insert/get/update/delete by primary key, plus predicate-filtered
    `rows()` for `db.query`/`db.count`/`db.delete_where`, with the
    constraint checking a `Schema` describes: reference existence,
    `unique`, and cascade/restrict on delete. With `Schema.empty()`
    (the default), every check is a no-op and this behaves exactly as
    M5 left it.

    `commit_batch` is the atomic entry point a `_FakeSession` uses:
    every insert/update/delete in one transaction validates against a
    scratch copy of the tables first, and nothing is applied to the
    real store unless the *whole* batch validates -- a mid-batch
    violation on the second row of a multi-row transaction must not
    leave the first row's insert applied, matching Pillar 4's "atomic
    transaction commit/rollback." `insert`/`update`/`delete` remain
    available standalone (single-statement atomicity) for direct,
    non-transactional use.
    """

    def __init__(self, schema: Schema | None = None) -> None:
        self._tables: dict[str, dict[str, dict[str, Any]]] = {}
        self.schema = schema or Schema.empty()

    def insert(self, table: str, pk: str, row: dict[str, Any]) -> None:
        self._check_write(self._tables, table, pk, row)
        self._tables.setdefault(table, {})[pk] = dict(row)

    def update(self, table: str, pk: str, row: dict[str, Any]) -> None:
        """Replaces an existing row's contents wholesale (the shape
        `db.update`'s generated `setattr`-then-commit produces). A
        missing row is a caller error, not a fake concern -- generated
        `db_update_tail` code only ever calls this after its own
        `session.get(...)` confirmed the row exists."""
        self._check_write(self._tables, table, pk, row, self_pk=pk)
        self._tables.setdefault(table, {})[pk] = dict(row)

    def delete(self, table: str, pk: str) -> None:
        for referencing_table, dep_pk in self._plan_delete(self._tables, table, pk):
            self._tables.get(referencing_table, {}).pop(dep_pk, None)
        self._tables.get(table, {}).pop(pk, None)

    def rows(self, table: str) -> list[tuple[str, dict[str, Any]]]:
        """Every `(pk, row)` pair in `table`, for predicate-filtered
        `db.query`/`db.count`/`db.delete_where` to iterate -- kept as
        an accessor rather than exposing `_tables` directly so
        `_FakeSession` doesn't reach into this class's storage
        internals."""
        return [(pk, dict(row)) for pk, row in self._tables.get(table, {}).items()]

    def commit_batch(
        self,
        inserts: list[tuple[str, str, dict[str, Any]]],
        deletes: list[tuple[str, str]],
        updates: list[tuple[str, str, dict[str, Any]]] | None = None,
    ) -> list[tuple[str, str]]:
        """Validates every insert, update, and delete against a scratch
        overlay, raising before touching the real store if any fails;
        applies the whole batch (including cascaded deletes) only once
        everything has validated. Returns the full list of
        `(table, pk)` pairs actually deleted, including cascades, so
        the caller can record each as its own transcript effect."""
        updates = updates or []
        overlay = {t: dict(rows) for t, rows in self._tables.items()}
        for table, pk, row in inserts:
            self._check_write(overlay, table, pk, row)
            overlay.setdefault(table, {})[pk] = dict(row)
        for table, pk, row in updates:
            self._check_write(overlay, table, pk, row, self_pk=pk)
            overlay.setdefault(table, {})[pk] = dict(row)

        all_deletes: list[tuple[str, str]] = []
        for table, pk in deletes:
            planned = self._plan_delete(overlay, table, pk)
            all_deletes.append((table, pk))
            all_deletes.extend(planned)
            for referencing_table, dep_pk in planned:
                overlay.get(referencing_table, {}).pop(dep_pk, None)
            overlay.get(table, {}).pop(pk, None)

        # Every check above raised before mutating `overlay`'s backing
        # store if it failed, so reaching here means the whole batch is
        # safe to apply for real.
        for table, pk, row in inserts:
            self._tables.setdefault(table, {})[pk] = dict(row)
        for table, pk, row in updates:
            self._tables.setdefault(table, {})[pk] = dict(row)
        for table, pk in all_deletes:
            self._tables.get(table, {}).pop(pk, None)
        return all_deletes

    def _check_write(
        self,
        tables: dict[str, dict[str, dict[str, Any]]],
        table: str,
        pk: str,
        row: dict[str, Any],
        self_pk: str | None = None,
    ) -> None:
        """Shared insert/update validation. `self_pk` (the row's own
        primary key, set only for updates) excludes that row from the
        primary-key-conflict and unique-reference-conflict checks
        below -- an update naturally collides with its own prior
        values otherwise, exactly the false positive Rust's
        `validate_write`/Java's `validateWrite` already guard against
        with the same `self_pk`-exclusion shape."""
        if pk in tables.get(table, {}) and pk != self_pk:
            raise UniqueViolation(f"{table}/{pk} already exists (primary key conflict)")
        table_schema = self.schema.tables.get(table)
        if table_schema is None:
            return
        for ref in table_schema.references:
            target_id = row.get(ref.python_attr)
            if target_id is None:
                continue
            if str(target_id) not in tables.get(ref.target_table_snake, {}):
                raise ReferenceViolation(
                    f"{table}.{ref.python_attr} references "
                    f"{ref.target_table_snake}/{target_id}, which does not exist"
                )
            if ref.unique:
                existing = tables.get(table, {})
                conflict = any(
                    existing_pk != pk and r.get(ref.python_attr) == target_id
                    for existing_pk, r in existing.items()
                )
                if conflict:
                    raise UniqueViolation(
                        f"{table}.{ref.python_attr} already has a row for "
                        f"{ref.target_table_snake}/{target_id}"
                    )

    def _plan_delete(
        self,
        tables: dict[str, dict[str, dict[str, Any]]],
        table: str,
        pk: str,
    ) -> list[tuple[str, str]]:
        """Every `(table, pk)` a delete of `table`/`pk` would cascade
        into, recursively, or raises if a `restrict` reference blocks
        it. Read-only against `tables`; the caller applies the result."""
        planned: list[tuple[str, str]] = []
        for referencing_table, ref in self.schema.references_to(table):
            referencing_rows = tables.get(referencing_table, {})
            dependents = [
                dep_pk
                for dep_pk, dep_row in referencing_rows.items()
                if str(dep_row.get(ref.python_attr)) == pk
            ]
            if not dependents:
                continue
            if ref.on_delete == "Restrict":
                raise ReferenceViolation(
                    f"cannot delete {table}/{pk}: {len(dependents)} row(s) in "
                    f"{referencing_table} still reference it (on_delete: restrict)"
                )
            for dep_pk in dependents:
                planned.append((referencing_table, dep_pk))
                planned.extend(self._plan_delete(tables, referencing_table, dep_pk))
        return planned

    def get(self, table: str, pk: str) -> dict[str, Any] | None:
        row = self._tables.get(table, {}).get(pk)
        return dict(row) if row is not None else None

    def count(self, table: str) -> int:
        return len(self._tables.get(table, {}))

    def snapshot(self) -> dict[str, dict[str, dict[str, Any]]]:
        return {table: dict(rows) for table, rows in self._tables.items()}


class FailureEngine:
    """Occurrence-counted `(effect, subject)` failure rules, `error`
    action only. Rules are `(effect, subject, occurrence) -> fail`;
    `occurrence` is 1-based, matching `ciac_sim::failure`'s own
    convention exactly, so the two stay comparable even though this one
    is a narrower restatement."""

    def __init__(self, rules: list[tuple[str, str | None, int]]) -> None:
        self._rules: set[tuple[str, str | None, int]] = set(rules)
        self._matched: set[tuple[str, str | None, int]] = set()
        self._counts: dict[tuple[str, str | None], int] = {}

    def should_fail(self, effect: str, subject: str | None) -> bool:
        key = (effect, subject)
        occurrence = self._counts.get(key, 0) + 1
        self._counts[key] = occurrence
        rule = (effect, subject, occurrence)
        if rule in self._rules:
            self._matched.add(rule)
            return True
        return False

    def unmatched(self) -> list[tuple[str, str | None, int]]:
        return sorted(self._rules - self._matched)


@dataclass
class _Message:
    message_id: str
    seq: int
    payload: dict[str, Any]


class FakeBroker:
    """Records publishes for the runner to hand to a worker's own
    generated `handle_message` explicitly -- there is no running
    subscription loop in this or any prior milestone (see module
    docstring); the runner remains the one that pumps delivery.

    v0.17 M7 adds ordering and independent queue groups: each publish
    to a subject gets the next sequence number in that subject's own
    ordered log; each `(subject, group)` keeps its own delivery cursor
    into that *same* log, so two workers on one stream each see every
    message, in publish order, without consuming each other's copy --
    Pillar 5's "independent groups each receive a copy."
    """

    def __init__(self) -> None:
        self.published: list[tuple[str, dict[str, Any]]] = []
        self._messages: dict[str, list[_Message]] = {}
        self._cursors: dict[tuple[str, str], int] = {}
        self._next_message_id = 1

    def record(self, subject: str, payload: dict[str, Any]) -> str:
        """Publishes `payload` to `subject`, returning a deterministic
        message ID (monotonically increasing per broker instance, not
        per subject -- distinguishing messages is this ID's only job;
        per-subject ordering is `seq`, tracked separately)."""
        self.published.append((subject, dict(payload)))
        seq = len(self._messages.get(subject, []))
        message_id = f"msg-{self._next_message_id}"
        self._next_message_id += 1
        self._messages.setdefault(subject, []).append(_Message(message_id, seq, dict(payload)))
        return message_id

    def take_next(self, subject: str, group: str) -> _Message | None:
        """The next message `group` hasn't yet been handed for
        `subject`, advancing that group's own cursor -- or `None` if
        the group is caught up. Independent of every other group's
        cursor on the same subject."""
        idx = self._cursors.get((subject, group), 0)
        messages = self._messages.get(subject, [])
        if idx >= len(messages):
            return None
        self._cursors[(subject, group)] = idx + 1
        return messages[idx]

    def drain(self, subject: str, group: str) -> list[_Message]:
        """Every message `group` hasn't yet been handed for `subject`,
        oldest first, advancing the cursor past all of them."""
        out: list[_Message] = []
        while (msg := self.take_next(subject, group)) is not None:
            out.append(msg)
        return out

    def pending_count(self, subject: str, group: str) -> int:
        """How many messages `group` hasn't yet been handed for
        `subject`, without advancing its cursor -- for quiescence
        checks, which must observe state, not consume it."""
        idx = self._cursors.get((subject, group), 0)
        return max(0, len(self._messages.get(subject, [])) - idx)


class VirtualClock:
    """A narrow Python restatement of `ciac_sim::clock::VirtualClock`
    (Rust, v0.17 M4) -- monotonic epoch-ms, advanced only by explicit
    runner calls, never wall time. Reconciling this with the canonical
    Rust clock (so this restatement stops existing) is the bounded
    child protocol M10 is scoped to build, same as `FailureEngine`."""

    def __init__(self, start_at_ms: int = 0) -> None:
        self._now_ms = start_at_ms

    def now_ms(self) -> int:
        return self._now_ms

    def advance_by(self, ms: int) -> None:
        assert ms >= 0, "virtual clock cannot move backward"
        self._now_ms += ms


class FakeCache:
    """Enough of `redis.asyncio.Redis`'s interface (with
    `decode_responses=True`) for generated cache-aside CRUD stores:
    `.get(key) -> str | None`, `.set(key, value, ex=seconds)`,
    `.delete(key)`. TTL is measured against the `VirtualClock` the
    world shares, not wall time -- the exact gap Pillar 6 names
    ("cache/token expiry uses wall time... requires a real week of
    sleeping" today); advancing virtual time here expires a key
    without a real sleep."""

    def __init__(self, clock: VirtualClock) -> None:
        self._clock = clock
        self._values: dict[str, str] = {}
        self._expire_at_ms: dict[str, int] = {}

    async def get(self, key: str) -> str | None:
        expire_at = self._expire_at_ms.get(key)
        if expire_at is not None and self._clock.now_ms() >= expire_at:
            self._values.pop(key, None)
            self._expire_at_ms.pop(key, None)
            return None
        return self._values.get(key)

    async def set(self, key: str, value: str, ex: int | None = None) -> None:
        self._values[key] = value
        if ex is not None:
            self._expire_at_ms[key] = self._clock.now_ms() + ex * 1000
        else:
            self._expire_at_ms.pop(key, None)

    async def delete(self, key: str) -> None:
        self._values.pop(key, None)
        self._expire_at_ms.pop(key, None)


class FakeObjectStore:
    """Enough of the generated `ObjectStore` wrapper's interface
    (`.put`/`.get`/`.delete`/`.list`) for v0.17 M8 -- an in-memory
    key/bytes map, no real S3/MinIO."""

    def __init__(self) -> None:
        self._objects: dict[str, bytes] = {}

    async def put(self, key: str, body: bytes, content_type: str = "application/octet-stream") -> None:
        self._objects[key] = bytes(body)

    async def get(self, key: str) -> bytes:
        return self._objects[key]

    async def delete(self, key: str) -> None:
        self._objects.pop(key, None)

    async def list(self, prefix: str) -> list[str]:
        return sorted(k for k in self._objects if k.startswith(prefix))


class FakeEmail:
    """Enough of the generated `Email` wrapper's interface (`.send`)
    for v0.17 M8 -- records sent messages instead of talking SMTP."""

    def __init__(self) -> None:
        self.sent: list[dict[str, str]] = []

    async def send(self, to: str, subject: str, body: str) -> None:
        self.sent.append({"to": to, "subject": subject, "body": body})


class FakeSearch:
    """Enough of the generated `Search` wrapper's interface
    (`.index`/`.search`/`.delete`) for v0.17 M8 -- an in-memory
    index/doc_id/document map with a narrow, disclosed query
    evaluator: it matches the *shape* `search.query` actually lowers to
    (`{"query": {"query_string": {"query": <text>}}}`, see
    `docs/expressions.md`) with a case-insensitive substring match over
    each document's JSON, not a real OpenSearch query language."""

    def __init__(self) -> None:
        self._docs: dict[str, dict[str, dict[str, Any]]] = {}

    async def index(self, index: str, doc_id: str, document: dict[str, Any]) -> None:
        self._docs.setdefault(index, {})[doc_id] = dict(document)

    async def search(self, index: str, query: dict[str, Any]) -> list[dict[str, Any]]:
        text = query.get("query", {}).get("query_string", {}).get("query", "")
        docs = list(self._docs.get(index, {}).values())
        if not text:
            return docs
        return [doc for doc in docs if text.lower() in json.dumps(doc).lower()]

    async def delete(self, index: str, doc_id: str) -> None:
        self._docs.get(index, {}).pop(doc_id, None)


class FakeHttpResponse:
    """Enough of `httpx.Response`'s interface (`.json()`) for a
    `external_http.request` call site (`(await self.http.post(..)).json()`,
    see `docs/expressions.md`)."""

    def __init__(self, json_body: Any) -> None:
        self._json = json_body

    def json(self) -> Any:
        return self._json


class FakeHttpClient:
    """A fixture-driven stand-in for `httpx.AsyncClient`, consuming the
    exact `GivenHttpResponse` shape `ciac_sim::scenario` already owns
    (`{"error": ..}` or `{"status": .., "json": ..}`) -- the same
    fixtures a portable scenario would declare for this instance drive
    this fake directly, not a second ad hoc format."""

    def __init__(self, responses: list[dict[str, Any]] | None = None) -> None:
        self._responses = list(responses or [])
        self._next = 0
        self.requests: list[tuple[str, Any]] = []

    async def post(self, url: str, json: Any = None, **_kwargs: Any) -> FakeHttpResponse:
        self.requests.append((url, json))
        if self._next >= len(self._responses):
            raise RuntimeError(
                f"no fixture response configured for external_http call #{self._next + 1} to {url}"
            )
        response = self._responses[self._next]
        self._next += 1
        if "error" in response:
            raise RuntimeError(f"simulated external_http failure: {response['error']}")
        return FakeHttpResponse(response["json"])


class AuthError(Exception):
    """A bearer token had no configured claims, or its configured
    expiry (against `VirtualClock`, not wall time) has passed. Mapped
    to a 401 by `auth.py.j2`'s `world`-guard, matching what real JWT/
    JWKS verification failure already does today."""


class FakeAuth:
    """Verifies a bearer token by direct lookup against claims the
    runner configured ahead of time, instead of real JWT/JWKS crypto --
    the disclosed simplification behind "dev-identity scope behavior
    passes with fake JWKS and no Keycloak process": rather than faking
    the JWKS HTTP round-trip `PyJWKClient` would make, this bypasses
    JWT/JWKS verification entirely. The observable outcome is the same
    (no Keycloak process, no real crypto, scope enforcement still
    real) by a more direct mechanism, not a literal JWKS fake -- see
    17UpdatePlan.md's M8 milestone entry."""

    def __init__(self, clock: VirtualClock) -> None:
        self._clock = clock
        self._tokens: dict[str, tuple[dict[str, Any], int | None]] = {}

    def issue(self, token: str, claims: dict[str, Any], expires_in_ms: int | None = None) -> None:
        expire_at = self._clock.now_ms() + expires_in_ms if expires_in_ms is not None else None
        self._tokens[token] = (claims, expire_at)

    def verify(self, token: str) -> dict[str, Any]:
        if token not in self._tokens:
            raise AuthError(f"no configured claims for bearer token {token!r}")
        claims, expire_at = self._tokens[token]
        if expire_at is not None and self._clock.now_ms() >= expire_at:
            raise AuthError(f"bearer token {token!r} has expired")
        return dict(claims)


@dataclass
class SimWorld:
    """The object `AppState.simulation(world)` stores. Duck-typed on
    purpose: `app/db.py`'s `get_sessionmaker` calls
    `world.fake_sessionmaker(instance)`; `app/queue.py`'s `publish`
    calls `world.publish(subject, payload)`. Nothing in generated code
    imports this class by name."""

    failure_rules: list[tuple[str, str | None, int]] = field(default_factory=list)
    schema: Schema = field(default_factory=Schema.empty)
    db: FakeDatabase = field(init=False)
    broker: FakeBroker = field(default_factory=FakeBroker)
    clock: VirtualClock = field(default_factory=VirtualClock)
    http_fixtures: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    transcript: list[dict[str, Any]] = field(default_factory=list)
    failures: FailureEngine = field(init=False)
    auth: FakeAuth = field(init=False)
    _caches: dict[str, FakeCache] = field(default_factory=dict, init=False)
    _object_stores: dict[str, FakeObjectStore] = field(default_factory=dict, init=False)
    _emails: dict[str, FakeEmail] = field(default_factory=dict, init=False)
    _searches: dict[str, FakeSearch] = field(default_factory=dict, init=False)
    _http_clients: dict[str, FakeHttpClient] = field(default_factory=dict, init=False)
    # 28UpdatePlan.md M3: the call-router registry, mirroring
    # `ciac_sim::world::SimWorld`'s `apis`/`call_depth` (Rust, M2)
    # exactly, adapted to this driver's single-threaded asyncio event
    # loop -- no lock is needed the way Rust's `Mutex<ApiRegistry>`
    # is, since nothing here ever runs two coroutines' bodies
    # concurrently on the same thread; a `try`/`finally` around the
    # depth counter is this file's RAII-guard equivalent to Rust's
    # `CallDepthGuard`.
    _apis: dict[tuple[str, str], Callable[[dict[str, Any]], Any]] = field(
        default_factory=dict, init=False
    )
    _call_depth: int = field(default=0, init=False)

    def __post_init__(self) -> None:
        self.failures = FailureEngine(self.failure_rules)
        self.db = FakeDatabase(self.schema)
        self.auth = FakeAuth(self.clock)

    def fake_sessionmaker(self, instance: str) -> Callable[[], "_FakeSession"]:
        def factory() -> "_FakeSession":
            return _FakeSession(self, instance)

        return factory

    def fake_cache(self, instance: str) -> FakeCache:
        if instance not in self._caches:
            self._caches[instance] = FakeCache(self.clock)
        return self._caches[instance]

    def fake_object_store(self, instance: str) -> FakeObjectStore:
        if instance not in self._object_stores:
            self._object_stores[instance] = FakeObjectStore()
        return self._object_stores[instance]

    def fake_email(self, instance: str) -> FakeEmail:
        if instance not in self._emails:
            self._emails[instance] = FakeEmail()
        return self._emails[instance]

    def fake_search(self, instance: str) -> FakeSearch:
        if instance not in self._searches:
            self._searches[instance] = FakeSearch()
        return self._searches[instance]

    def fake_http_client(self, instance: str) -> FakeHttpClient:
        if instance not in self._http_clients:
            self._http_clients[instance] = FakeHttpClient(self.http_fixtures.get(instance))
        return self._http_clients[instance]

    async def publish(self, subject: str, payload: dict[str, Any]) -> None:
        self.transcript.append({"effect": "broker.publish", "subject": subject})
        self.broker.record(subject, payload)

    # 28UpdatePlan.md M3 (Pillar 2/3): a `call <Service>.<Api>` pipeline
    # step routed here instead of over real HTTP, mirroring `ciac_sim::
    # world::SimWorld::register_api`/`call_checked` (Rust, M2) exactly.
    MAX_CALL_DEPTH = 64

    def register_api(
        self, service: str, api: str, handler: Callable[[dict[str, Any]], Any]
    ) -> None:
        """Registers `handler` as `service`'s `api`, the target
        `call_checked` resolves a routed call against. A system driver
        (M3+) calls this once per api, in service declaration order,
        before any scenario runs; re-registering the same `(service,
        api)` replaces the earlier handler rather than erroring,
        matching how a driver would simply rebuild the world (and
        re-register everything) between scenario runs rather than
        asking this registry to detect staleness itself."""
        self._apis[(service, api)] = handler

    async def call_checked(
        self, caller: str, callee_service: str, api: str, req: dict[str, Any]
    ) -> Any:
        """Routes a `call <Service>.<Api>` step -- inline and
        synchronous (`await`ed straight through) on the caller's own
        logical coroutine, exactly as production's typed call client
        behaves, just against the registered handler instead of real
        HTTP. `call`s count against the `call.request` failure
        vocabulary the same way `db.commit`/`broker.publish` do; an
        injected failure fires before the handler ever runs, and an
        unregistered `(callee_service, api)` is a clear error rather
        than a silent no-op -- the same "fail closed on a missing seam"
        discipline `FakeHttpClient` already uses for an unmatched
        fixture. The handler's own return value or raised exception
        passes through verbatim, matching production's own "the
        callee's real response or real error, not a synthesized one."

        `_call_depth` is not a cycle detector -- `ciac-sema`'s own
        `CycleDetection` pass already refuses a call cycle at compile
        time (`EdgeKind::ServiceCall` is one of the edge kinds its
        combined flow-graph check considers, confirmed live via
        `tests/ui/service-call-cycle.ciac`), so a cycle can never reach
        a compiled program's own routed calls. This guard exists for
        the case that check cannot cover -- a hand-built registration
        (this file's own tests, or a future non-generated driver) whose
        registered handlers call each other in a way the compiler
        never saw -- turning what would otherwise be an unrecoverable
        `RecursionError` into a graceful, named exception."""
        if self.failures.should_fail("call.request", api):
            raise RuntimeError("simulated call.request failure (injected by FailureEngine)")
        handler = self._apis.get((callee_service, api))
        if handler is None:
            raise RoutingError(
                f"no handler registered for {callee_service}.{api} (called from {caller})"
            )
        if self._call_depth >= self.MAX_CALL_DEPTH:
            raise RoutingError(
                f"routed call depth exceeded {self.MAX_CALL_DEPTH} calling "
                f"{callee_service}.{api} from {caller} -- ciac-sema's own CycleDetection pass "
                f"already refuses a call cycle at compile time, so this guards against runaway "
                f"recursion in a hand-built registration, not a reachable cycle in a compiled "
                f"program"
            )
        self._call_depth += 1
        try:
            return await handler(req)
        finally:
            self._call_depth -= 1

    async def deliver(self, subject: str, group: str, handle_message) -> int:
        """Drains every undelivered message for `(subject, group)` and
        calls `handle_message(payload_dict)` on each, oldest first,
        applying `broker.ack` failure rules after each successful
        handling: a matched rule means the ack for that occurrence was
        lost, so the broker (having never seen it acknowledged)
        redelivers the *same* message again -- the real effects it
        already committed stay committed, per Pillar 5's "acknowledgement
        lost after effects committed." Returns the number of
        `handle_message` invocations, including redeliveries, so a
        caller can distinguish "delivered once" from "delivered twice."
        """
        invocations = 0
        for msg in self.broker.drain(subject, group):
            await handle_message(msg.payload)
            invocations += 1
            self.transcript.append({"effect": "broker.ack", "subject": subject})
            while self.failures.should_fail("broker.ack", subject):
                self.transcript.append({"effect": "broker.redeliver", "subject": subject})
                await handle_message(msg.payload)
                invocations += 1
        return invocations

    async def deliver_counting_attempts(
        self, subject: str, group: str, handle_once, max_retries: int
    ) -> int:
        """Like `deliver`, but drives `handle_once` (the generated
        `handle_message_once`, M1's confirmed real per-attempt entry
        point) through its own retry loop here instead of delegating
        to the generated `handle_message`'s internal one -- exactly
        what M4's `retry_eligible` was built for ("used by a future
        scheduler that drives `handle_message_once` directly... to
        match the real generated `handle_message` loop's exact bound").
        Returns the total number of `handle_once` attempts across every
        drained message, including retries and lost-ack redeliveries --
        the count a scenario's `worker_attempts` expectation checks,
        which `deliver`'s own `invocations` (top-level calls only) can't
        report since a retrying `handle_message` hides its internal
        attempt count from the caller."""
        total_attempts = 0
        for msg in self.broker.drain(subject, group):
            total_attempts += await self._attempt_until_done(handle_once, msg.payload, max_retries)
            self.transcript.append({"effect": "broker.ack", "subject": subject})
            while self.failures.should_fail("broker.ack", subject):
                self.transcript.append({"effect": "broker.redeliver", "subject": subject})
                total_attempts += await self._attempt_until_done(handle_once, msg.payload, max_retries)
        return total_attempts

    @staticmethod
    async def _attempt_until_done(handle_once, payload: dict[str, Any], max_retries: int) -> int:
        attempts = 0
        for attempt in range(max_retries + 1):  # matches retry_eligible(attempt, max_retries)
            attempts += 1
            try:
                await handle_once(payload)
                return attempts
            except Exception:
                if attempt >= max_retries:
                    return attempts
        return attempts


def _compile_predicate(whereclause: Any) -> Callable[[dict[str, Any]], bool]:
    """M9: compiles a `db.query`/`db.count`/`db.delete_where`
    statement's own `.whereclause` (as `where_chain`, `ciac-backend-
    python::lower.rs`, actually emits -- confirmed live against real
    generated statements built from `SQLAlchemy` 2.0, not assumed)
    into a `row_dict -> bool` closure, without a real SQL engine.
    `None` (no `.where()` calls at all) matches every row.

    The four shapes `where_chain` ever produces, recursed into here:
    `BooleanClauseList` (multiple chained `.where()` calls, ANDed --
    `where_chain` only ever emits `AND`, there is no generated `OR`),
    `Grouping` (the `.contains(...)` wrapper), `AsBoolean` (a bare or
    `~`-negated truthy column -- `where_chain`'s ruff-E712 dodge for
    `Eq true`/`NotEq false`/`Eq false`/`NotEq true`), and
    `BinaryExpression` (every other operator, including `contains`
    once unwrapped from its `Grouping`). Row/target values are
    compared as plain Python objects -- unlike Java's own `World.
    jsonEq` workaround for a `Long`-vs-`Integer` mismatch, nothing
    here round-trips through a second, differently-typed decoder: both
    the stored row (via `FakeDatabase`) and the statement's own bound
    literal (via `where_chain`'s `PredValue` rendering) are native
    Python values the whole way.
    """
    if whereclause is None:
        return lambda row: True

    from sqlalchemy.sql import operators
    from sqlalchemy.sql.elements import AsBoolean, BinaryExpression, BooleanClauseList, Grouping

    if isinstance(whereclause, BooleanClauseList):
        sub = [_compile_predicate(clause) for clause in whereclause.clauses]
        return lambda row: all(f(row) for f in sub)

    if isinstance(whereclause, Grouping):
        return _compile_predicate(whereclause.element)

    if isinstance(whereclause, AsBoolean):
        field = whereclause.element.key
        want_true = whereclause.operator is operators.is_true
        return lambda row: bool(row.get(field)) is want_true

    if isinstance(whereclause, BinaryExpression):
        from sqlalchemy.sql.elements import False_, True_

        field = whereclause.left.key
        op = whereclause.operator
        # `Model.bool_field == some_bool` (reached whenever the compared
        # value is a variable, not a `BoolLit` -- `where_chain`'s own
        # bare-truthy-column shortcut only fires for a literal `true`/
        # `false`) coerces its right side to a `True_`/`False_`
        # singleton instead of a `BindParameter`, even though the
        # operator is still plain `eq`/`ne` -- found live against
        # query-verbs.ciac's own generated `Notes.active ==
        # filter.active`. Neither singleton carries a `.value`.
        if isinstance(whereclause.right, True_):
            target = True
        elif isinstance(whereclause.right, False_):
            target = False
        else:
            target = whereclause.right.value
        ops: dict[Any, Callable[[Any, Any], bool]] = {
            operators.eq: lambda a, b: a == b,
            operators.ne: lambda a, b: a != b,
            operators.lt: lambda a, b: a < b,
            operators.le: lambda a, b: a <= b,
            operators.gt: lambda a, b: a > b,
            operators.ge: lambda a, b: a >= b,
            operators.contains_op: lambda a, b: b in (a or ""),
        }
        for candidate, fn in ops.items():
            if op is candidate:
                return lambda row: fn(row.get(field), target)
        raise TypeError(f"_compile_predicate: unhandled operator {op!r}")

    raise TypeError(f"_compile_predicate: unhandled whereclause shape {type(whereclause)!r}")


@dataclass
class _FakeResult:
    """Enough of `sqlalchemy.engine.Result`'s interface for the three
    shapes `query_tail` (`ciac-backend-python::lower.rs`) generates:
    `.scalars().all()` (`DbQuery`), `.scalar_one()` (`DbCount`), and
    `.rowcount` (`DbDeleteWhere`)."""

    _rows: list[Any] = field(default_factory=list)
    _scalar: Any = None
    _rowcount: int = 0

    def scalars(self) -> "_FakeResult":
        return self

    def all(self) -> list[Any]:
        return self._rows

    def scalar_one(self) -> Any:
        return self._scalar

    @property
    def rowcount(self) -> int:
        return self._rowcount


class _FakeSession:
    """Enough of `sqlalchemy.ext.asyncio.AsyncSession`'s interface for
    generated code that calls `.add(obj)`/`await .delete(obj)`/
    `await .get(Model, pk)`/`await .execute(stmt)` then
    `await .commit()`/`await .rollback()` inside
    `async with sessionmaker() as session:` -- exactly what the
    `transaction { db.insert(..); }` lowering, a cache-aside CRUD
    store's read path, and `db.update`/`db.query`/`db.count`/
    `db.delete_where`'s own generated code (see `db_update_tail`/
    `query_tail`, `ciac-backend-python::lower.rs`) emit.

    M9 closes the gap M5-M8 disclosed here (".scalars`/attribute-
    mutation-based updates remain unsupported"): `.get()` now returns
    a *tracked* object (recorded in `self._tracked` alongside a
    snapshot of the row it was built from, not the plain fresh-and-
    forgotten one M5-M8 returned) so that `db_update_tail`'s own
    `setattr(_row, _k, _v)` pattern -- there is no separate `.add()`
    call after a `.get()`-then-mutate, real `AsyncSession` relies on
    its own identity map to notice the change -- has something to be
    noticed by. `.commit()` recomputes each tracked object's current
    column values and diffs them against the snapshot taken at
    `.get()` time, persisting a `FakeDatabase.update()` (and a
    `db.update` transcript effect) only for objects that actually
    changed -- a plain read-only `db.get()` inside a transaction that
    also writes elsewhere must not manufacture a spurious update, the
    same way real `AsyncSession`'s dirty-tracking emits zero `UPDATE`
    statements for an untouched row. `.execute()` handles the
    `select`/`sql_delete` statements `db.query`/`db.count`/
    `db.delete_where` build, via `_compile_predicate` above.
    """

    def __init__(self, world: SimWorld, instance: str) -> None:
        self._world = world
        self._instance = instance
        self._pending_adds: list[Any] = []
        self._pending_deletes: list[Any] = []
        self._tracked: list[tuple[Any, dict[str, Any]]] = []

    def add(self, obj: Any) -> None:
        self._pending_adds.append(obj)

    async def get(self, model: type, pk: Any) -> Any | None:
        table = model.__tablename__
        row = self._world.db.get(table, str(pk))
        if row is None:
            return None
        obj = model(**row)
        self._tracked.append((obj, row))
        return obj

    async def delete(self, obj: Any) -> None:
        self._pending_deletes.append(obj)

    async def execute(self, stmt: Any) -> _FakeResult:
        from sqlalchemy import Delete

        if isinstance(stmt, Delete):
            table = stmt.table.name
            predicate = _compile_predicate(stmt.whereclause)
            matched = [pk for pk, row in self._world.db.rows(table) if predicate(row)]
            for _pk in matched:
                if self._world.failures.should_fail("db.commit", table):
                    raise RuntimeError("simulated db.commit failure (injected by FailureEngine)")
            for pk in matched:
                # `delete()` applies (and cascades) immediately, rather
                # than going through `commit_batch` -- matching
                # `db_delete_tail`'s own generated shape for
                # `DbDeleteWhere`, which commits per-statement, not
                # inside an ambient batch.
                self._world.db.delete(table, pk)
                self._world.transcript.append({"effect": "db.delete", "subject": table})
            return _FakeResult(_rowcount=len(matched))

        table = stmt.get_final_froms()[0].name
        predicate = _compile_predicate(stmt.whereclause)
        matched_rows = [row for _pk, row in self._world.db.rows(table) if predicate(row)]
        entity = stmt.column_descriptions[0]["entity"] if stmt.column_descriptions else None
        if entity is None:
            return _FakeResult(_scalar=len(matched_rows))
        return _FakeResult(_rows=[entity(**row) for row in matched_rows])

    async def commit(self) -> None:
        # The subject a failure rule targets is the table being written,
        # not the db instance name -- with only one declared `db`
        # instance in this checkpoint's fixture, the instance name can't
        # distinguish "PlaceOrder's own transaction" from "the worker's
        # retried transaction" the way Pillar 7's own `subject` (a
        # stream name, for broker effects) distinguishes different
        # streams on one broker.
        pending = self._pending_adds or self._pending_deletes or [obj for obj, _snap in self._tracked]
        subject = pending[0].__table__.name if pending else self._instance
        if self._world.failures.should_fail("db.commit", subject):
            self._pending_adds.clear()
            self._pending_deletes.clear()
            self._tracked.clear()
            raise RuntimeError("simulated db.commit failure (injected by FailureEngine)")

        inserts = []
        for obj in self._pending_adds:
            table = obj.__table__.name
            pk_col = next(iter(obj.__table__.primary_key.columns)).name
            row = {c.name: getattr(obj, c.name) for c in obj.__table__.columns}
            inserts.append((table, str(row[pk_col]), row))
        updates = []
        for obj, snapshot in self._tracked:
            row = {c.name: getattr(obj, c.name) for c in obj.__table__.columns}
            if row == snapshot:
                continue  # untouched since .get() -- no UPDATE, matching real dirty-tracking
            table = obj.__table__.name
            pk_col = next(iter(obj.__table__.primary_key.columns)).name
            updates.append((table, str(row[pk_col]), row))
        deletes = []
        for obj in self._pending_deletes:
            table = obj.__table__.name
            pk_col = next(iter(obj.__table__.primary_key.columns)).name
            deletes.append((table, str(getattr(obj, pk_col))))

        # commit_batch validates the whole transaction against a
        # scratch overlay before applying any of it -- a violation here
        # raises with nothing yet written to the real store, so no
        # partial-insert/update cleanup is needed on the exception path.
        all_deletes = self._world.db.commit_batch(inserts, deletes, updates)

        for table, _pk, _row in inserts:
            self._world.transcript.append({"effect": "db.insert", "subject": table})
        for table, _pk, _row in updates:
            self._world.transcript.append({"effect": "db.update", "subject": table})
        for table, _pk in all_deletes:
            self._world.transcript.append({"effect": "db.delete", "subject": table})
        self._pending_adds.clear()
        self._pending_deletes.clear()
        self._tracked.clear()

    async def rollback(self) -> None:
        self._pending_adds.clear()
        self._pending_deletes.clear()
        self._tracked.clear()

    async def __aenter__(self) -> "_FakeSession":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> bool:
        if exc_type is not None:
            await self.rollback()
        return False
