"""The v0.17 Python simulation driver, not generated by `ciac build`.

M5 shipped the narrow checkpoint slice: insert-only database effects
inside a `transaction` block, a single broker publish, and worker-
retry-driven failure injection at `db.commit`, proven against
`examples/sim-vertical-slice.ciac`.

M6 (this revision) makes `FakeDatabase` schema-aware: reference
existence, `unique` (including a `Reference<T>` marked `unique: true`,
domain-orders.ciac's 1:1 `LineItem.order` shape), and cascade/restrict
delete, using the same constraint metadata `ciac_sim::SimPlan` already
derives from validated IR (v0.17 M2) -- not a second, hand-rolled
schema description. `crates/ciac-sim/examples/dump_plan.rs` prints that
`SimPlan` as JSON for a `.ciac` file; `Schema.load` below parses it.

Why not reflect constraints out of the generated project's own
SQLAlchemy models instead of shelling out to `dump_plan`? Traced empirically
for v0.17 M6: generated `app/models.py` columns are plain, constraint-
free `Mapped[str]` declarations (`customer_id: Mapped[str] =
mapped_column(Text)`, no `ForeignKey`, no `UniqueConstraint`) -- real
FK/cascade/unique enforcement lives only in migration SQL text (an
`ALTER TABLE ... ADD CONSTRAINT ...` a fake has no reason to parse) and,
canonically, in `SimPlan` itself. Reflecting SQLAlchemy metadata would
find nothing there to reflect.

Still out of scope for M6, disclosed:

- Indexes: `index: true` on a plain scalar field is silently discarded
  by the compiler itself (M1's finding) -- there is nothing for a fake
  to enforce that production doesn't already no-op. `SimPlan` does not
  carry index metadata for this reason.
- Constraint-violation-to-409/422 HTTP mapping: domain-orders.ciac's
  own header comment discloses this mapping doesn't exist on the real
  Postgres path either ("`InvalidOrder`/insufficient-funds-style
  failures surface as a raw 500, not a mapped 409/422"). Inventing the
  mapping only in the fake would make the fake strictly more capable
  than production -- the "mock rot" risk this document's own Risks
  section names -- so the exception types below are unmapped,
  matching today's real behavior on both targets.
- `on_update` cascade/restrict: no generated code path ever updates a
  primary key (IDs are immutable UUIDs, per M1's finding), so there is
  no real behavior to match; `Schema` records the action but nothing
  triggers it.
- The CI-regenerated fidelity-ratchet parity report (this document's
  Verification strategy section) comparing this fake's outcomes
  against a live Postgres compose run: still Docker-delegated, same
  disclosed gap as v0.11 M3's kafka broker-delivery proof. M6's own
  proof (`sim/pyrunner/run_domain_orders.py`) is infrastructure-free
  by construction, not fake-versus-real.

Also still out of scope, unchanged from M5:

- No broker redelivery-after-total-failure, no ordering/groups/
  duplicate delivery -- Pillar 5's full fake is M7's job.
- The `FailureEngine` below is a narrow Python restatement of
  `ciac_sim::failure::FailureEngine` (Rust, v0.17 M4), covering only
  the `error` action this checkpoint's scenario needs. `ciac-sim`
  remains the canonical, tested implementation of the full failure
  vocabulary and scheduling order; reconciling the two into one
  shared implementation (so this file stops existing as a separate
  restatement) is the bounded child protocol M10 is scoped to build.
- No generic JSON-scenario interpreter; `run_vertical_slice.py` and
  `run_domain_orders.py` each drive a hand-written translation of
  their scenario's steps. Feeding `ciac-sim`'s own `Scenario` schema
  directly to a generated runner is M9/M10's job.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Callable


class ReferenceViolation(Exception):
    """A `Reference<T>` field pointed at a row that doesn't exist, or a
    delete was blocked by an `on_delete: restrict` reference. Unmapped
    to any HTTP status -- see the module docstring."""


class UniqueViolation(Exception):
    """A `Reference<T> { unique: true }` field's target already has a
    row. Unmapped to any HTTP status -- see the module docstring."""


def to_snake_case(name: str) -> str:
    """Matches `ciac_sim::plan::snake_case` (Rust) exactly, which is
    itself documented there as matching `heck::ToSnakeCase` closely
    enough for CIaC's ASCII identifiers -- so a `SimPlan` table name
    ("LineItems") lands on the same string as the generated
    `__tablename__` ("line_items") this fake indexes by."""
    out: list[str] = []
    for i, c in enumerate(name):
        if c.isupper():
            if i != 0:
                out.append("_")
            out.append(c.lower())
        else:
            out.append(c)
    return "".join(out)


@dataclass
class ReferenceColumn:
    """One `Reference<T>` column's constraint metadata, resolved to the
    generated Python attribute name (`<field>_id`) and the target
    table's snake-case name -- both conventions confirmed empirically
    against real generated `app/models.py` output, not assumed."""

    python_attr: str
    target_table_snake: str
    on_delete: str  # "Restrict" | "Cascade"
    unique: bool


@dataclass
class TableSchema:
    references: list[ReferenceColumn] = field(default_factory=list)


class Schema:
    """Parses a `SimPlan` JSON document (see `dump_plan.rs`) into a
    lookup keyed by the generated project's own snake_case table
    names. `Schema.empty()` (no constraints) preserves M5's behavior
    for callers that don't need M6's checking -- `FakeDatabase` without
    a schema is exactly as permissive as it was before this revision.
    """

    def __init__(self, tables: dict[str, TableSchema]) -> None:
        self.tables = tables

    @classmethod
    def empty(cls) -> "Schema":
        return cls({})

    @classmethod
    def from_plan_json(cls, plan: dict[str, Any]) -> "Schema":
        tables: dict[str, TableSchema] = {}
        table_key_to_snake = {
            t["key"]: to_snake_case(t["name"]) for t in plan["tables"]
        }
        for t in plan["tables"]:
            snake = table_key_to_snake[t["key"]]
            schema = TableSchema()
            for col in t["columns"]:
                ty = col["ty"]
                if ty.get("type") == "Reference" and ty.get("target_table"):
                    schema.references.append(
                        ReferenceColumn(
                            python_attr=f"{col['name']}_id",
                            target_table_snake=table_key_to_snake[ty["target_table"]],
                            on_delete=ty["on_delete"],
                            unique=ty["unique"],
                        )
                    )
            tables[snake] = schema
        return cls(tables)

    def references_to(self, table_snake: str) -> list[tuple[str, ReferenceColumn]]:
        """Every `(referencing_table, ReferenceColumn)` pointing at
        `table_snake` -- what a delete of a row in `table_snake` must
        check."""
        return [
            (referencing_table, ref)
            for referencing_table, schema in self.tables.items()
            for ref in schema.references
            if ref.target_table_snake == table_snake
        ]


class FakeDatabase:
    """Insert/get/delete by primary key, with the constraint checking a
    `Schema` describes: reference existence, `unique`, and cascade/
    restrict on delete. With `Schema.empty()` (the default), every
    check is a no-op and this behaves exactly as M5 left it.

    `commit_batch` is the atomic entry point a `_FakeSession` uses:
    every insert/delete in one transaction validates against a scratch
    copy of the tables first, and nothing is applied to the real store
    unless the *whole* batch validates -- a mid-batch violation on the
    second row of a multi-row transaction must not leave the first
    row's insert applied, matching Pillar 4's "atomic transaction
    commit/rollback." `insert`/`delete` remain available standalone
    (single-statement atomicity) for direct, non-transactional use.
    """

    def __init__(self, schema: Schema | None = None) -> None:
        self._tables: dict[str, dict[str, dict[str, Any]]] = {}
        self.schema = schema or Schema.empty()

    def insert(self, table: str, pk: str, row: dict[str, Any]) -> None:
        self._check_insert(self._tables, table, pk, row)
        self._tables.setdefault(table, {})[pk] = dict(row)

    def delete(self, table: str, pk: str) -> None:
        for referencing_table, dep_pk in self._plan_delete(self._tables, table, pk):
            self._tables.get(referencing_table, {}).pop(dep_pk, None)
        self._tables.get(table, {}).pop(pk, None)

    def commit_batch(
        self,
        inserts: list[tuple[str, str, dict[str, Any]]],
        deletes: list[tuple[str, str]],
    ) -> list[tuple[str, str]]:
        """Validates every insert and delete against a scratch overlay,
        raising before touching the real store if any fails; applies
        the whole batch (including cascaded deletes) only once
        everything has validated. Returns the full list of
        `(table, pk)` pairs actually deleted, including cascades, so
        the caller can record each as its own transcript effect."""
        overlay = {t: dict(rows) for t, rows in self._tables.items()}
        for table, pk, row in inserts:
            self._check_insert(overlay, table, pk, row)
            overlay.setdefault(table, {})[pk] = dict(row)

        all_deletes: list[tuple[str, str]] = []
        for table, pk in deletes:
            planned = self._plan_delete(overlay, table, pk)
            all_deletes.append((table, pk))
            all_deletes.extend(planned)
            for referencing_table, dep_pk in planned:
                overlay.get(referencing_table, {}).pop(dep_pk, None)
            overlay.get(table, {}).pop(pk, None)

        # Every check above raised before mutating `overlay`'s backing
        # store if it failed, so reaching here means the whole batch is
        # safe to apply for real.
        for table, pk, row in inserts:
            self._tables.setdefault(table, {})[pk] = dict(row)
        for table, pk in all_deletes:
            self._tables.get(table, {}).pop(pk, None)
        return all_deletes

    def _check_insert(
        self,
        tables: dict[str, dict[str, dict[str, Any]]],
        table: str,
        pk: str,
        row: dict[str, Any],
    ) -> None:
        if pk in tables.get(table, {}):
            raise UniqueViolation(f"{table}/{pk} already exists (primary key conflict)")
        table_schema = self.schema.tables.get(table)
        if table_schema is None:
            return
        for ref in table_schema.references:
            target_id = row.get(ref.python_attr)
            if target_id is None:
                continue
            if str(target_id) not in tables.get(ref.target_table_snake, {}):
                raise ReferenceViolation(
                    f"{table}.{ref.python_attr} references "
                    f"{ref.target_table_snake}/{target_id}, which does not exist"
                )
            if ref.unique:
                existing = tables.get(table, {})
                conflict = any(
                    existing_pk != pk and r.get(ref.python_attr) == target_id
                    for existing_pk, r in existing.items()
                )
                if conflict:
                    raise UniqueViolation(
                        f"{table}.{ref.python_attr} already has a row for "
                        f"{ref.target_table_snake}/{target_id}"
                    )

    def _plan_delete(
        self,
        tables: dict[str, dict[str, dict[str, Any]]],
        table: str,
        pk: str,
    ) -> list[tuple[str, str]]:
        """Every `(table, pk)` a delete of `table`/`pk` would cascade
        into, recursively, or raises if a `restrict` reference blocks
        it. Read-only against `tables`; the caller applies the result."""
        planned: list[tuple[str, str]] = []
        for referencing_table, ref in self.schema.references_to(table):
            referencing_rows = tables.get(referencing_table, {})
            dependents = [
                dep_pk
                for dep_pk, dep_row in referencing_rows.items()
                if str(dep_row.get(ref.python_attr)) == pk
            ]
            if not dependents:
                continue
            if ref.on_delete == "Restrict":
                raise ReferenceViolation(
                    f"cannot delete {table}/{pk}: {len(dependents)} row(s) in "
                    f"{referencing_table} still reference it (on_delete: restrict)"
                )
            for dep_pk in dependents:
                planned.append((referencing_table, dep_pk))
                planned.extend(self._plan_delete(tables, referencing_table, dep_pk))
        return planned

    def get(self, table: str, pk: str) -> dict[str, Any] | None:
        row = self._tables.get(table, {}).get(pk)
        return dict(row) if row is not None else None

    def count(self, table: str) -> int:
        return len(self._tables.get(table, {}))

    def snapshot(self) -> dict[str, dict[str, dict[str, Any]]]:
        return {table: dict(rows) for table, rows in self._tables.items()}


class FailureEngine:
    """Occurrence-counted `(effect, subject)` failure rules, `error`
    action only. Rules are `(effect, subject, occurrence) -> fail`;
    `occurrence` is 1-based, matching `ciac_sim::failure`'s own
    convention exactly, so the two stay comparable even though this one
    is a narrower restatement."""

    def __init__(self, rules: list[tuple[str, str | None, int]]) -> None:
        self._rules: set[tuple[str, str | None, int]] = set(rules)
        self._matched: set[tuple[str, str | None, int]] = set()
        self._counts: dict[tuple[str, str | None], int] = {}

    def should_fail(self, effect: str, subject: str | None) -> bool:
        key = (effect, subject)
        occurrence = self._counts.get(key, 0) + 1
        self._counts[key] = occurrence
        rule = (effect, subject, occurrence)
        if rule in self._rules:
            self._matched.add(rule)
            return True
        return False

    def unmatched(self) -> list[tuple[str, str | None, int]]:
        return sorted(self._rules - self._matched)


@dataclass
class _Message:
    message_id: str
    seq: int
    payload: dict[str, Any]


class FakeBroker:
    """Records publishes for the runner to hand to a worker's own
    generated `handle_message` explicitly -- there is no running
    subscription loop in this or any prior milestone (see module
    docstring); the runner remains the one that pumps delivery.

    v0.17 M7 adds ordering and independent queue groups: each publish
    to a subject gets the next sequence number in that subject's own
    ordered log; each `(subject, group)` keeps its own delivery cursor
    into that *same* log, so two workers on one stream each see every
    message, in publish order, without consuming each other's copy --
    Pillar 5's "independent groups each receive a copy."
    """

    def __init__(self) -> None:
        self.published: list[tuple[str, dict[str, Any]]] = []
        self._messages: dict[str, list[_Message]] = {}
        self._cursors: dict[tuple[str, str], int] = {}
        self._next_message_id = 1

    def record(self, subject: str, payload: dict[str, Any]) -> str:
        """Publishes `payload` to `subject`, returning a deterministic
        message ID (monotonically increasing per broker instance, not
        per subject -- distinguishing messages is this ID's only job;
        per-subject ordering is `seq`, tracked separately)."""
        self.published.append((subject, dict(payload)))
        seq = len(self._messages.get(subject, []))
        message_id = f"msg-{self._next_message_id}"
        self._next_message_id += 1
        self._messages.setdefault(subject, []).append(_Message(message_id, seq, dict(payload)))
        return message_id

    def take_next(self, subject: str, group: str) -> _Message | None:
        """The next message `group` hasn't yet been handed for
        `subject`, advancing that group's own cursor -- or `None` if
        the group is caught up. Independent of every other group's
        cursor on the same subject."""
        idx = self._cursors.get((subject, group), 0)
        messages = self._messages.get(subject, [])
        if idx >= len(messages):
            return None
        self._cursors[(subject, group)] = idx + 1
        return messages[idx]

    def drain(self, subject: str, group: str) -> list[_Message]:
        """Every message `group` hasn't yet been handed for `subject`,
        oldest first, advancing the cursor past all of them."""
        out: list[_Message] = []
        while (msg := self.take_next(subject, group)) is not None:
            out.append(msg)
        return out


class VirtualClock:
    """A narrow Python restatement of `ciac_sim::clock::VirtualClock`
    (Rust, v0.17 M4) -- monotonic epoch-ms, advanced only by explicit
    runner calls, never wall time. Reconciling this with the canonical
    Rust clock (so this restatement stops existing) is the bounded
    child protocol M10 is scoped to build, same as `FailureEngine`."""

    def __init__(self, start_at_ms: int = 0) -> None:
        self._now_ms = start_at_ms

    def now_ms(self) -> int:
        return self._now_ms

    def advance_by(self, ms: int) -> None:
        assert ms >= 0, "virtual clock cannot move backward"
        self._now_ms += ms


class FakeCache:
    """Enough of `redis.asyncio.Redis`'s interface (with
    `decode_responses=True`) for generated cache-aside CRUD stores:
    `.get(key) -> str | None`, `.set(key, value, ex=seconds)`,
    `.delete(key)`. TTL is measured against the `VirtualClock` the
    world shares, not wall time -- the exact gap Pillar 6 names
    ("cache/token expiry uses wall time... requires a real week of
    sleeping" today); advancing virtual time here expires a key
    without a real sleep."""

    def __init__(self, clock: VirtualClock) -> None:
        self._clock = clock
        self._values: dict[str, str] = {}
        self._expire_at_ms: dict[str, int] = {}

    async def get(self, key: str) -> str | None:
        expire_at = self._expire_at_ms.get(key)
        if expire_at is not None and self._clock.now_ms() >= expire_at:
            self._values.pop(key, None)
            self._expire_at_ms.pop(key, None)
            return None
        return self._values.get(key)

    async def set(self, key: str, value: str, ex: int | None = None) -> None:
        self._values[key] = value
        if ex is not None:
            self._expire_at_ms[key] = self._clock.now_ms() + ex * 1000
        else:
            self._expire_at_ms.pop(key, None)

    async def delete(self, key: str) -> None:
        self._values.pop(key, None)
        self._expire_at_ms.pop(key, None)


class FakeObjectStore:
    """Enough of the generated `ObjectStore` wrapper's interface
    (`.put`/`.get`/`.delete`/`.list`) for v0.17 M8 -- an in-memory
    key/bytes map, no real S3/MinIO."""

    def __init__(self) -> None:
        self._objects: dict[str, bytes] = {}

    async def put(self, key: str, body: bytes, content_type: str = "application/octet-stream") -> None:
        self._objects[key] = bytes(body)

    async def get(self, key: str) -> bytes:
        return self._objects[key]

    async def delete(self, key: str) -> None:
        self._objects.pop(key, None)

    async def list(self, prefix: str) -> list[str]:
        return sorted(k for k in self._objects if k.startswith(prefix))


class FakeEmail:
    """Enough of the generated `Email` wrapper's interface (`.send`)
    for v0.17 M8 -- records sent messages instead of talking SMTP."""

    def __init__(self) -> None:
        self.sent: list[dict[str, str]] = []

    async def send(self, to: str, subject: str, body: str) -> None:
        self.sent.append({"to": to, "subject": subject, "body": body})


class FakeSearch:
    """Enough of the generated `Search` wrapper's interface
    (`.index`/`.search`/`.delete`) for v0.17 M8 -- an in-memory
    index/doc_id/document map with a narrow, disclosed query
    evaluator: it matches the *shape* `search.query` actually lowers to
    (`{"query": {"query_string": {"query": <text>}}}`, see
    `docs/expressions.md`) with a case-insensitive substring match over
    each document's JSON, not a real OpenSearch query language."""

    def __init__(self) -> None:
        self._docs: dict[str, dict[str, dict[str, Any]]] = {}

    async def index(self, index: str, doc_id: str, document: dict[str, Any]) -> None:
        self._docs.setdefault(index, {})[doc_id] = dict(document)

    async def search(self, index: str, query: dict[str, Any]) -> list[dict[str, Any]]:
        text = query.get("query", {}).get("query_string", {}).get("query", "")
        docs = list(self._docs.get(index, {}).values())
        if not text:
            return docs
        return [doc for doc in docs if text.lower() in json.dumps(doc).lower()]

    async def delete(self, index: str, doc_id: str) -> None:
        self._docs.get(index, {}).pop(doc_id, None)


class FakeHttpResponse:
    """Enough of `httpx.Response`'s interface (`.json()`) for a
    `external_http.request` call site (`(await self.http.post(..)).json()`,
    see `docs/expressions.md`)."""

    def __init__(self, json_body: Any) -> None:
        self._json = json_body

    def json(self) -> Any:
        return self._json


class FakeHttpClient:
    """A fixture-driven stand-in for `httpx.AsyncClient`, consuming the
    exact `GivenHttpResponse` shape `ciac_sim::scenario` already owns
    (`{"error": ..}` or `{"status": .., "json": ..}`) -- the same
    fixtures a portable scenario would declare for this instance drive
    this fake directly, not a second ad hoc format."""

    def __init__(self, responses: list[dict[str, Any]] | None = None) -> None:
        self._responses = list(responses or [])
        self._next = 0
        self.requests: list[tuple[str, Any]] = []

    async def post(self, url: str, json: Any = None, **_kwargs: Any) -> FakeHttpResponse:
        self.requests.append((url, json))
        if self._next >= len(self._responses):
            raise RuntimeError(
                f"no fixture response configured for external_http call #{self._next + 1} to {url}"
            )
        response = self._responses[self._next]
        self._next += 1
        if "error" in response:
            raise RuntimeError(f"simulated external_http failure: {response['error']}")
        return FakeHttpResponse(response["json"])


class AuthError(Exception):
    """A bearer token had no configured claims, or its configured
    expiry (against `VirtualClock`, not wall time) has passed. Mapped
    to a 401 by `auth.py.j2`'s `world`-guard, matching what real JWT/
    JWKS verification failure already does today."""


class FakeAuth:
    """Verifies a bearer token by direct lookup against claims the
    runner configured ahead of time, instead of real JWT/JWKS crypto --
    the disclosed simplification behind "dev-identity scope behavior
    passes with fake JWKS and no Keycloak process": rather than faking
    the JWKS HTTP round-trip `PyJWKClient` would make, this bypasses
    JWT/JWKS verification entirely. The observable outcome is the same
    (no Keycloak process, no real crypto, scope enforcement still
    real) by a more direct mechanism, not a literal JWKS fake -- see
    17UpdatePlan.md's M8 milestone entry."""

    def __init__(self, clock: VirtualClock) -> None:
        self._clock = clock
        self._tokens: dict[str, tuple[dict[str, Any], int | None]] = {}

    def issue(self, token: str, claims: dict[str, Any], expires_in_ms: int | None = None) -> None:
        expire_at = self._clock.now_ms() + expires_in_ms if expires_in_ms is not None else None
        self._tokens[token] = (claims, expire_at)

    def verify(self, token: str) -> dict[str, Any]:
        if token not in self._tokens:
            raise AuthError(f"no configured claims for bearer token {token!r}")
        claims, expire_at = self._tokens[token]
        if expire_at is not None and self._clock.now_ms() >= expire_at:
            raise AuthError(f"bearer token {token!r} has expired")
        return dict(claims)


@dataclass
class SimWorld:
    """The object `AppState.simulation(world)` stores. Duck-typed on
    purpose: `app/db.py`'s `get_sessionmaker` calls
    `world.fake_sessionmaker(instance)`; `app/queue.py`'s `publish`
    calls `world.publish(subject, payload)`. Nothing in generated code
    imports this class by name."""

    failure_rules: list[tuple[str, str | None, int]] = field(default_factory=list)
    schema: Schema = field(default_factory=Schema.empty)
    db: FakeDatabase = field(init=False)
    broker: FakeBroker = field(default_factory=FakeBroker)
    clock: VirtualClock = field(default_factory=VirtualClock)
    http_fixtures: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    transcript: list[dict[str, Any]] = field(default_factory=list)
    failures: FailureEngine = field(init=False)
    auth: FakeAuth = field(init=False)
    _caches: dict[str, FakeCache] = field(default_factory=dict, init=False)
    _object_stores: dict[str, FakeObjectStore] = field(default_factory=dict, init=False)
    _emails: dict[str, FakeEmail] = field(default_factory=dict, init=False)
    _searches: dict[str, FakeSearch] = field(default_factory=dict, init=False)
    _http_clients: dict[str, FakeHttpClient] = field(default_factory=dict, init=False)

    def __post_init__(self) -> None:
        self.failures = FailureEngine(self.failure_rules)
        self.db = FakeDatabase(self.schema)
        self.auth = FakeAuth(self.clock)

    def fake_sessionmaker(self, instance: str) -> Callable[[], "_FakeSession"]:
        def factory() -> "_FakeSession":
            return _FakeSession(self, instance)

        return factory

    def fake_cache(self, instance: str) -> FakeCache:
        if instance not in self._caches:
            self._caches[instance] = FakeCache(self.clock)
        return self._caches[instance]

    def fake_object_store(self, instance: str) -> FakeObjectStore:
        if instance not in self._object_stores:
            self._object_stores[instance] = FakeObjectStore()
        return self._object_stores[instance]

    def fake_email(self, instance: str) -> FakeEmail:
        if instance not in self._emails:
            self._emails[instance] = FakeEmail()
        return self._emails[instance]

    def fake_search(self, instance: str) -> FakeSearch:
        if instance not in self._searches:
            self._searches[instance] = FakeSearch()
        return self._searches[instance]

    def fake_http_client(self, instance: str) -> FakeHttpClient:
        if instance not in self._http_clients:
            self._http_clients[instance] = FakeHttpClient(self.http_fixtures.get(instance))
        return self._http_clients[instance]

    async def publish(self, subject: str, payload: dict[str, Any]) -> None:
        self.transcript.append({"effect": "broker.publish", "subject": subject})
        self.broker.record(subject, payload)

    async def deliver(self, subject: str, group: str, handle_message) -> int:
        """Drains every undelivered message for `(subject, group)` and
        calls `handle_message(payload_dict)` on each, oldest first,
        applying `broker.ack` failure rules after each successful
        handling: a matched rule means the ack for that occurrence was
        lost, so the broker (having never seen it acknowledged)
        redelivers the *same* message again -- the real effects it
        already committed stay committed, per Pillar 5's "acknowledgement
        lost after effects committed." Returns the number of
        `handle_message` invocations, including redeliveries, so a
        caller can distinguish "delivered once" from "delivered twice."
        """
        invocations = 0
        for msg in self.broker.drain(subject, group):
            await handle_message(msg.payload)
            invocations += 1
            self.transcript.append({"effect": "broker.ack", "subject": subject})
            while self.failures.should_fail("broker.ack", subject):
                self.transcript.append({"effect": "broker.redeliver", "subject": subject})
                await handle_message(msg.payload)
                invocations += 1
        return invocations


class _FakeSession:
    """Enough of `sqlalchemy.ext.asyncio.AsyncSession`'s interface for
    generated code that calls `.add(obj)`/`await .delete(obj)`/
    `await .get(Model, pk)` then `await .commit()`/`await .rollback()`
    inside `async with sessionmaker() as session:` -- exactly what the
    `transaction { db.insert(..); }` lowering and a cache-aside CRUD
    store's read path (see `customer_store.py`-shaped generated code)
    emit. `.scalars`/attribute-mutation-based updates remain
    unsupported; a fixture that needed them would be out of the
    M5/M6/M7-disclosed scope, not a bug in this class.
    """

    def __init__(self, world: SimWorld, instance: str) -> None:
        self._world = world
        self._instance = instance
        self._pending_adds: list[Any] = []
        self._pending_deletes: list[Any] = []

    def add(self, obj: Any) -> None:
        self._pending_adds.append(obj)

    async def get(self, model: type, pk: Any) -> Any | None:
        table = model.__tablename__
        row = self._world.db.get(table, str(pk))
        return model(**row) if row is not None else None

    async def delete(self, obj: Any) -> None:
        self._pending_deletes.append(obj)

    async def commit(self) -> None:
        # The subject a failure rule targets is the table being written,
        # not the db instance name -- with only one declared `db`
        # instance in this checkpoint's fixture, the instance name can't
        # distinguish "PlaceOrder's own transaction" from "the worker's
        # retried transaction" the way Pillar 7's own `subject` (a
        # stream name, for broker effects) distinguishes different
        # streams on one broker.
        pending = self._pending_adds or self._pending_deletes
        subject = pending[0].__table__.name if pending else self._instance
        if self._world.failures.should_fail("db.commit", subject):
            self._pending_adds.clear()
            self._pending_deletes.clear()
            raise RuntimeError("simulated db.commit failure (injected by FailureEngine)")

        inserts = []
        for obj in self._pending_adds:
            table = obj.__table__.name
            pk_col = next(iter(obj.__table__.primary_key.columns)).name
            row = {c.name: getattr(obj, c.name) for c in obj.__table__.columns}
            inserts.append((table, str(row[pk_col]), row))
        deletes = []
        for obj in self._pending_deletes:
            table = obj.__table__.name
            pk_col = next(iter(obj.__table__.primary_key.columns)).name
            deletes.append((table, str(getattr(obj, pk_col))))

        # commit_batch validates the whole transaction against a
        # scratch overlay before applying any of it -- a violation here
        # raises with nothing yet written to the real store, so no
        # partial-insert cleanup is needed on the exception path.
        all_deletes = self._world.db.commit_batch(inserts, deletes)

        for table, _pk, _row in inserts:
            self._world.transcript.append({"effect": "db.insert", "subject": table})
        for table, _pk in all_deletes:
            self._world.transcript.append({"effect": "db.delete", "subject": table})
        self._pending_adds.clear()
        self._pending_deletes.clear()

    async def rollback(self) -> None:
        self._pending_adds.clear()
        self._pending_deletes.clear()

    async def __aenter__(self) -> "_FakeSession":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> bool:
        if exc_type is not None:
            await self.rollback()
        return False
