"""The v0.17 M5 checkpoint's minimal Python simulation driver.

Not generated by `ciac build` -- 17UpdatePlan.md's Rollout strategy
calls this checkpoint "roughly M1-M4 plus a narrow cut of the
relational/broker fakes and a minimal runner, not the whole version."
This module is that narrow cut: it proves the `AppState.production()`/
`AppState.simulation(world)` port (v0.17 M3) and the target-neutral
scheduling primitives (v0.17 M4, `ciac-sim`) compose against a *real*
generated Python project, using only what `examples/sim-vertical-
slice.ciac`'s own handlers need: insert-only database effects inside a
`transaction` block, a single broker publish, and worker-retry-driven
failure injection at `db.commit`.

What this narrow cut deliberately does not attempt:

- No update/delete/query verbs, no constraints/indexes/cascades --
  Pillar 4's full reference engine is M6's job.
- No broker redelivery-after-total-failure, no ordering/groups/
  duplicate delivery -- Pillar 5's full fake is M7's job.
- The `FailureEngine` below is a narrow Python restatement of
  `ciac_sim::failure::FailureEngine` (Rust, v0.17 M4), covering only
  the `error` action this checkpoint's scenario needs. `ciac-sim`
  remains the canonical, tested implementation of the full failure
  vocabulary and scheduling order; reconciling the two into one
  shared implementation (so this file stops existing as a separate
  restatement) is the bounded child protocol M10 is scoped to build,
  not this checkpoint.
- No generic JSON-scenario interpreter. `run_vertical_slice.py` drives
  a hand-written translation of `sim/vertical-slice.ciac-sim.json`'s
  steps; it does not parse and execute arbitrary scenario JSON. Feeding
  ciac-sim's own `Scenario` schema directly to a generated runner is
  M9/M10's job.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable


class FakeDatabase:
    """Insert/read-by-primary-key only -- the M5-disclosed slice of
    Pillar 4's full reference engine. No required-field/unique/
    reference validation yet; that is explicitly M6's job, not this
    checkpoint's."""

    def __init__(self) -> None:
        self._tables: dict[str, dict[str, dict[str, Any]]] = {}

    def insert(self, table: str, pk: str, row: dict[str, Any]) -> None:
        self._tables.setdefault(table, {})[pk] = dict(row)

    def get(self, table: str, pk: str) -> dict[str, Any] | None:
        row = self._tables.get(table, {}).get(pk)
        return dict(row) if row is not None else None

    def count(self, table: str) -> int:
        return len(self._tables.get(table, {}))

    def snapshot(self) -> dict[str, dict[str, dict[str, Any]]]:
        return {table: dict(rows) for table, rows in self._tables.items()}


class FailureEngine:
    """Occurrence-counted `(effect, subject)` failure rules, `error`
    action only. Rules are `(effect, subject, occurrence) -> fail`;
    `occurrence` is 1-based, matching `ciac_sim::failure`'s own
    convention exactly, so the two stay comparable even though this one
    is a narrower restatement."""

    def __init__(self, rules: list[tuple[str, str | None, int]]) -> None:
        self._rules: set[tuple[str, str | None, int]] = set(rules)
        self._matched: set[tuple[str, str | None, int]] = set()
        self._counts: dict[tuple[str, str | None], int] = {}

    def should_fail(self, effect: str, subject: str | None) -> bool:
        key = (effect, subject)
        occurrence = self._counts.get(key, 0) + 1
        self._counts[key] = occurrence
        rule = (effect, subject, occurrence)
        if rule in self._rules:
            self._matched.add(rule)
            return True
        return False

    def unmatched(self) -> list[tuple[str, str | None, int]]:
        return sorted(self._rules - self._matched)


class FakeBroker:
    """Records publishes for the runner to hand to a worker's own
    generated `handle_message` explicitly -- there is no running
    subscription loop in this checkpoint (see module docstring)."""

    def __init__(self) -> None:
        self.published: list[tuple[str, dict[str, Any]]] = []

    def record(self, subject: str, payload: dict[str, Any]) -> None:
        self.published.append((subject, dict(payload)))


@dataclass
class SimWorld:
    """The object `AppState.simulation(world)` stores. Duck-typed on
    purpose: `app/db.py`'s `get_sessionmaker` calls
    `world.fake_sessionmaker(instance)`; `app/queue.py`'s `publish`
    calls `world.publish(subject, payload)`. Nothing in generated code
    imports this class by name."""

    failure_rules: list[tuple[str, str | None, int]] = field(default_factory=list)
    db: FakeDatabase = field(default_factory=FakeDatabase)
    broker: FakeBroker = field(default_factory=FakeBroker)
    transcript: list[dict[str, Any]] = field(default_factory=list)
    failures: FailureEngine = field(init=False)

    def __post_init__(self) -> None:
        self.failures = FailureEngine(self.failure_rules)

    def fake_sessionmaker(self, instance: str) -> Callable[[], "_FakeSession"]:
        def factory() -> "_FakeSession":
            return _FakeSession(self, instance)

        return factory

    async def publish(self, subject: str, payload: dict[str, Any]) -> None:
        self.transcript.append({"effect": "broker.publish", "subject": subject})
        self.broker.record(subject, payload)


class _FakeSession:
    """Enough of `sqlalchemy.ext.asyncio.AsyncSession`'s interface for
    generated code that only ever calls `.add(obj)` then
    `await .commit()`/`await .rollback()` inside `async with
    sessionmaker() as session:` -- exactly the `transaction { db.insert
    (..); }` lowering emits (see `docs/expressions.md`). `.get`/
    `.scalars`/`.delete`/attribute-mutation-based updates are
    unsupported on purpose; a fixture that needed them would be out of
    the M5-disclosed scope, not a bug in this class.
    """

    def __init__(self, world: SimWorld, instance: str) -> None:
        self._world = world
        self._instance = instance
        self._pending: list[Any] = []

    def add(self, obj: Any) -> None:
        self._pending.append(obj)

    async def commit(self) -> None:
        # The subject a failure rule targets is the table being written,
        # not the db instance name -- with only one declared `db`
        # instance in this checkpoint's fixture, the instance name can't
        # distinguish "PlaceOrder's own transaction" from "the worker's
        # retried transaction" the way Pillar 7's own `subject` (a
        # stream name, for broker effects) distinguishes different
        # streams on one broker.
        subject = self._pending[0].__table__.name if self._pending else self._instance
        if self._world.failures.should_fail("db.commit", subject):
            self._pending.clear()
            raise RuntimeError("simulated db.commit failure (injected by FailureEngine)")
        for obj in self._pending:
            table = obj.__table__.name
            pk_col = next(iter(obj.__table__.primary_key.columns)).name
            row = {c.name: getattr(obj, c.name) for c in obj.__table__.columns}
            self._world.db.insert(table, str(row[pk_col]), row)
            self._world.transcript.append({"effect": "db.insert", "subject": table})
        self._pending.clear()

    async def rollback(self) -> None:
        self._pending.clear()

    async def __aenter__(self) -> "_FakeSession":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> bool:
        if exc_type is not None:
            await self.rollback()
        return False
