//! v0.8 external-backend protocol M2: exercises
//! `ciac_codegen::external::ExternalBackend` against the real,
//! compiled `stub-backend` fixture (`tests/bin/stub-backend.rs`) for
//! every documented scenario, plus a regression check that a target
//! with no matching executable at all still fails clearly.
//!
//! Each scenario uses `ExternalBackend::with_executable(...)` pointed
//! directly at the compiled stub binary (`env!("CARGO_BIN_EXE_stub-backend")`,
//! `cargo test`'s standard way to locate a sibling test binary) and
//! selects its behavior via `GenOptions::project_name` — the stub
//! reads that field instead of an env var, so nothing here needs to
//! mutate `$PATH` or any process-wide env var (which would need
//! `unsafe`, forbidden workspace-wide) and every test is free to run
//! concurrently with the others.

use ciac_codegen::external::ExternalBackend;
use ciac_codegen::{Backend, GenOptions};
use ciac_integration_tests::compile;

fn sample_ir() -> ciac_ir::NormalizedIr {
    let (ir, diags) = compile(
        "service Notes;\nuse { db Postgres; }\nrecord Note { id: Uuid; title: String; }\ncrud Note;\n",
    );
    ir.unwrap_or_else(|| panic!("compiles: {:?}", diags.codes()))
}

fn stub_backend() -> ExternalBackend {
    ExternalBackend::with_executable("stub", env!("CARGO_BIN_EXE_stub-backend"))
}

fn opts_with_mode(mode: &str) -> GenOptions {
    GenOptions {
        project_name: Some(mode.to_owned()),
    }
}

#[test]
fn echo_mode_round_trips_real_data() {
    let ir = sample_ir();
    let project = stub_backend()
        .generate(&ir, &opts_with_mode("echo"))
        .expect("echo mode succeeds");
    assert_eq!(
        project.get("stub-output.txt"),
        Some("generated for target: stub")
    );
    assert_eq!(project.notes, vec!["generated by stub-backend".to_owned()]);
}

#[test]
fn fail_mode_surfaces_nonzero_exit_clearly() {
    let ir = sample_ir();
    let err = stub_backend()
        .generate(&ir, &opts_with_mode("fail"))
        .expect_err("fail mode fails");
    assert!(err.to_string().contains("exited with"), "{err}");
}

#[test]
fn garbage_mode_is_distinguished_from_a_valid_but_wrong_shape_response() {
    let ir = sample_ir();
    let err = stub_backend()
        .generate(&ir, &opts_with_mode("garbage"))
        .expect_err("garbage mode fails");
    assert!(
        err.to_string()
            .contains("did not write a valid CodegenResponse"),
        "{err}"
    );
}

#[test]
fn bad_version_mode_is_refused_despite_being_structurally_valid() {
    let ir = sample_ir();
    let err = stub_backend()
        .generate(&ir, &opts_with_mode("bad-version"))
        .expect_err("version mismatch fails");
    assert!(err.to_string().contains("protocol version 999"), "{err}");
}

#[test]
fn unknown_target_with_no_matching_executable_fails_clearly() {
    // Regression check on `ExternalBackend::new`'s real $PATH-based
    // resolution: doesn't touch PATH/env at all, so it's safe
    // alongside every other test regardless of thread scheduling
    // (assuming nothing on the real $PATH happens to be named
    // `ciac-backend-...` for this nonsense target).
    let ir = sample_ir();
    let backend = ExternalBackend::new("definitely-not-a-real-target-regression-check");
    let err = backend
        .generate(&ir, &GenOptions::default())
        .expect_err("no such executable exists");
    let message = err.to_string();
    assert!(
        message.contains("definitely-not-a-real-target-regression-check"),
        "{message}"
    );
}
