//! v0.15 M5: GitHub Actions workflow emission (`ciac build --deploy ci`).
//!
//! Deliberately small, as the plan calls for: a `test` job that runs
//! exactly what `ciac verify` runs locally (both read the same
//! `TargetInfo::validate`/`ci_test_steps` pair, v0.22 M1 — one source,
//! not two kept in sync by hand), one `build-image` job per declared
//! service (matrix over
//! service dirs in a multi-service system) that builds the Dockerfile
//! unconditionally and pushes only on a version tag, and a
//! `compose-smoke` job that boots the full dev stack and polls every
//! service's `/health` the same way `ciac verify --live` already does
//! locally. GitHub Actions only — the shape is a template away from
//! GitLab CI once real usage says that's worth it (see 15UpdatePlan.md).
//!
//! Registry credentials are never emitted, only referenced:
//! `secrets.REGISTRY_URL`/`REGISTRY_USERNAME`/`REGISTRY_PASSWORD` are
//! GitHub Actions repository secrets the deploying team configures
//! themselves. `.github/workflows/ci.yml` is an owned file like any
//! other generated file — a team that hand-edits it gets a sidecar on
//! the next regeneration, not a silent overwrite.

use crate::model::{build_system, SystemModel};
use crate::GenOptions;
use ciac_ir::NormalizedIr;

/// `ciac build --deploy ci --semantic-baseline <path>` (v0.18 M3): the
/// two repo-root-relative paths the generated `semantic-compat` job
/// needs. Both must already be relative — the caller (`ciac/src/
/// commands.rs`) rejects absolute paths before constructing this, since
/// 18UpdatePlan.md Pillar 4 requires "developer absolute paths never
/// enter YAML".
#[derive(Debug)]
pub struct SemanticGate<'a> {
    pub source_file: &'a str,
    pub baseline: &'a str,
}

/// Builds `.github/workflows/ci.yml` for the program. `image_prefix`
/// defaults to the program's own project name when `None`, matching
/// `--deploy k8s`'s convention. `semantic_gate` (v0.18 M3) adds a
/// breaking-change compatibility gate that must pass before `test` runs.
/// `ci_test_steps` is the target's own literal step YAML
/// (`TargetInfo::ci_test_steps`, v0.22 M1) — this module no longer
/// knows which targets exist, only how to embed whatever steps it's
/// handed; the caller (`ciac/src/commands.rs`) resolves it via the
/// registry, falling back to [`GENERIC_TEST_STEPS`] for external
/// backends (v0.8 M2+), which bring their own verification story.
pub fn build(
    ir: &NormalizedIr,
    ci_test_steps: &str,
    image_prefix: Option<&str>,
    semantic_gate: Option<SemanticGate<'_>>,
) -> Vec<(String, String)> {
    let system = build_system(ir, &GenOptions::default());
    let image_prefix = image_prefix.unwrap_or(&system.project_name).to_owned();
    let workflow = render_workflow(
        &system,
        ci_test_steps,
        &image_prefix,
        semantic_gate.as_ref(),
    );
    vec![(".github/workflows/ci.yml".to_owned(), workflow)]
}

fn render_workflow(
    system: &SystemModel,
    test_steps: &str,
    image_prefix: &str,
    semantic_gate: Option<&SemanticGate<'_>>,
) -> String {
    let mut out = String::new();
    out.push_str("# Generated by CIaC (`ciac build --deploy ci`). Owned file: a hand-edited\n");
    out.push_str("# copy survives regeneration as a sidecar, same as any other owned file.\n");
    out.push_str("name: CI\n\n");
    out.push_str("on:\n  push:\n    branches: [main]\n    tags: [\"v*\"]\n  pull_request:\n    branches: [main]\n\n");
    out.push_str("jobs:\n");
    if let Some(gate) = semantic_gate {
        out.push_str(&render_semantic_compat_job(gate));
        out.push('\n');
        out.push_str(
            "  test:\n    needs: semantic-compat\n    runs-on: ubuntu-latest\n    steps:\n",
        );
    } else {
        out.push_str("  test:\n    runs-on: ubuntu-latest\n    steps:\n");
    }
    out.push_str("      - uses: actions/checkout@v4\n");
    out.push_str(test_steps);
    out.push('\n');

    out.push_str(&render_build_image_job(system, image_prefix));
    out.push('\n');
    out.push_str(&render_compose_smoke_job(system));
    out
}

/// The breaking-change compatibility gate (18UpdatePlan.md Pillar 4):
/// installs the exact CIaC release this workflow was generated by
/// (never "latest" — reproducible across every run of this commit),
/// runs the real consumer-aware semantic differ against the checked-in
/// baseline, uploads the complete typed changelist whether the gate
/// passes or fails, and only then enforces the pass/fail verdict — so
/// the changelist is always available for review even on a hard
/// failure. Never writes, updates, or commits the baseline itself: the
/// only way to accept a break is `ciac baseline --update
/// --accept-breaking`, run by a human before this workflow ever sees
/// the commit.
fn render_semantic_compat_job(gate: &SemanticGate<'_>) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let source_file = gate.source_file;
    let baseline = gate.baseline;
    let mut out = String::from(
        "  semantic-compat:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n",
    );
    out.push_str(&format!(
        "      - name: Install ciac v{version} (pinned, never latest)\n        run: |\n          curl -fsSL https://github.com/jrcalgo/ciac/releases/download/v{version}/ciac-linux-x86_64 -o /usr/local/bin/ciac\n          chmod +x /usr/local/bin/ciac\n"
    ));
    out.push_str(&format!(
        "      - name: Semantic compatibility gate\n        run: |\n          set +e\n          ciac diff {source_file} --semantic --deny-breaking --baseline {baseline} --json > semantic-changelist.json\n          echo \"gate_exit=$?\" >> \"$GITHUB_ENV\"\n          exit 0\n"
    ));
    out.push_str(
        "      - name: Upload changelist\n        if: always()\n        uses: actions/upload-artifact@v4\n        with:\n          name: semantic-changelist\n          path: semantic-changelist.json\n",
    );
    out.push_str(
        "      - name: Job summary\n        if: always()\n        run: |\n          {\n            echo \"## Semantic compatibility\"\n            if [ -s semantic-changelist.json ]; then cat semantic-changelist.json; else echo \"no changelist produced (compile error — see above)\"; fi\n          } >> \"$GITHUB_STEP_SUMMARY\"\n          trailer=$(git log -1 --pretty=%B | grep -m1 '^ciac-breaking:' || true)\n          if [ -n \"$trailer\" ]; then echo \"note: $trailer (informational only; the gate result above is never overridden by this trailer)\" >> \"$GITHUB_STEP_SUMMARY\"; fi\n",
    );
    out.push_str(
        "      - name: Enforce gate\n        run: exit \"$gate_exit\"\n        env:\n          gate_exit: ${{ env.gate_exit }}\n",
    );
    out
}

// Not `"\` + indented continuation lines: a backslash-newline in a Rust
// string literal strips *all* leading whitespace on the next line, not
// just the newline, which silently de-indents the first YAML step.
//
// The per-language steps (once `PYTHON_TEST_STEPS`/`RUST_TEST_STEPS`
// here) now live in their own backend crates as
// `TargetInfo::ci_test_steps` (v0.22 M1) — this is the one survivor,
// since it's genuinely target-neutral scaffolding, not a specific
// language's steps.
pub const GENERIC_TEST_STEPS: &str = "      # No built-in verification for this backend — fill in the\n      # target's own build/test commands here.\n      - run: echo \"add this backend's test commands\"\n";

/// One `build-image` job per declared service, matrixed over service
/// directories in a multi-service system (each has its own
/// Dockerfile); a single job for single-service programs. Every push
/// builds the image (proving the Dockerfile still works); only a
/// `v*` tag push logs in and pushes it, using placeholder
/// `secrets.REGISTRY_*` — never real credentials, per the plan's
/// explicit "ciac emits the shape" line.
fn render_build_image_job(system: &SystemModel, image_prefix: &str) -> String {
    let mut out = String::from("  build-image:\n    needs: test\n    runs-on: ubuntu-latest\n");
    if system.multi {
        out.push_str("    strategy:\n      matrix:\n        service:\n");
        for ctx in &system.services {
            out.push_str(&format!("          - {}\n", ctx.dir));
        }
        out.push_str("    steps:\n      - uses: actions/checkout@v4\n");
        out.push_str(&format!(
            "      - name: Build {image_prefix}-${{{{ matrix.service }}}}\n        run: docker build -t {image_prefix}-${{{{ matrix.service }}}}:${{{{ github.sha }}}} ./${{{{ matrix.service }}}}\n"
        ));
        out.push_str(&render_push_step(&format!(
            "{image_prefix}-${{{{ matrix.service }}}}"
        )));
    } else {
        out.push_str("    steps:\n      - uses: actions/checkout@v4\n");
        out.push_str(&format!(
            "      - name: Build {image_prefix}\n        run: docker build -t {image_prefix}:${{{{ github.sha }}}} .\n"
        ));
        out.push_str(&render_push_step(image_prefix));
    }
    out
}

fn render_push_step(image: &str) -> String {
    format!(
        "      - name: Push {image} on release tag\n        if: startsWith(github.ref, 'refs/tags/v')\n        env:\n          REGISTRY_URL: ${{{{ secrets.REGISTRY_URL }}}}\n          REGISTRY_USERNAME: ${{{{ secrets.REGISTRY_USERNAME }}}}\n          REGISTRY_PASSWORD: ${{{{ secrets.REGISTRY_PASSWORD }}}}\n        run: |\n          echo \"$REGISTRY_PASSWORD\" | docker login \"$REGISTRY_URL\" -u \"$REGISTRY_USERNAME\" --password-stdin\n          docker tag {image}:${{{{ github.sha }}}} \"$REGISTRY_URL/{image}:${{{{ github.ref_name }}}}\"\n          docker push \"$REGISTRY_URL/{image}:${{{{ github.ref_name }}}}\"\n"
    )
}

/// Boots the full dev compose stack and polls every service's
/// `/health` — the same acceptance bar `ciac verify --system --live`
/// already proves locally (`crates/ciac/src/commands.rs`), just
/// running it in CI too. Ports come straight from the same
/// [`SystemModel`] the compose file itself was rendered from, so this
/// stays correct as services are added.
fn render_compose_smoke_job(system: &SystemModel) -> String {
    let mut out = String::from(
        "  compose-smoke:\n    needs: test\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: docker compose up -d --build\n",
    );
    for ctx in &system.services {
        out.push_str(&format!(
            "      - name: Wait for {}'s /health\n        run: |\n          for i in $(seq 1 30); do\n            curl -sf http://localhost:{}/health && exit 0\n            sleep 2\n          done\n          echo \"{} never became healthy\" >&2\n          docker compose logs\n          exit 1\n",
            ctx.service_name, ctx.host_port, ctx.service_name,
        ));
    }
    out.push_str("      - run: docker compose down\n        if: always()\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn compile(src: &str) -> NormalizedIr {
        let mut sources = ciac_diagnostics::SourceMap::new();
        let file = sources.add_file("test.ciac", src);
        let mut diags = ciac_diagnostics::Diagnostics::new();
        let program = ciac_syntax::parse(src, file, &mut diags);
        ciac_sema::analyze(&program, &mut diags)
            .unwrap_or_else(|| panic!("compiles: {:?}", diags.codes()))
    }

    // v0.22 M1: this module no longer owns per-language step text (it
    // lives in each backend crate's own `TargetInfo::ci_test_steps`
    // now) — these two fixtures stand in for "some target's real
    // steps" so the embedding mechanism itself stays under test.
    const PYTHON_STEPS_FIXTURE: &str = "      - uses: astral-sh/setup-uv@v3\n      - run: uv sync\n      - run: uv run ruff check .\n      - run: uv run pytest -q\n";
    const RUST_STEPS_FIXTURE: &str = "      - uses: dtolnay/rust-toolchain@stable\n      - run: cargo check\n        env:\n          RUSTFLAGS: \"-D warnings\"\n      - run: cargo test -q --lib\n";

    #[test]
    fn single_service_python_gets_uv_test_job_and_one_image() {
        let ir = compile("service Ping;\nrecord Msg { id: Uuid; }\napi Echo: Msg { method: POST; path: \"/echo\"; }\npipeline Echo: Return;\n");
        let files = build(&ir, PYTHON_STEPS_FIXTURE, None, None);
        assert_eq!(files.len(), 1);
        let (path, content) = &files[0];
        assert_eq!(path, ".github/workflows/ci.yml");
        assert!(content.contains("uses: astral-sh/setup-uv@v3"));
        assert!(content.contains("uv run pytest -q"));
        assert!(content.contains("docker build -t ping:${{ github.sha }} ."));
        assert!(!content.contains("strategy:"));
        assert!(content.contains("secrets.REGISTRY_URL"));
        assert!(
            !content.contains("REGISTRY_PASSWORD }}\"")
                || content.contains("secrets.REGISTRY_PASSWORD")
        );
        assert!(content.contains("curl -sf http://localhost:8000/health"));
        assert!(!content.contains("semantic-compat"));
    }

    #[test]
    fn single_service_rust_gets_cargo_test_job() {
        let ir = compile("service Ping;\nrecord Msg { id: Uuid; }\napi Echo: Msg { method: POST; path: \"/echo\"; }\npipeline Echo: Return;\n");
        let files = build(&ir, RUST_STEPS_FIXTURE, Some("myimg"), None);
        let (_, content) = &files[0];
        assert!(content.contains("dtolnay/rust-toolchain@stable"));
        assert!(content.contains("cargo test -q --lib"));
        assert!(content.contains("docker build -t myimg:${{ github.sha }} ."));
    }

    #[test]
    fn semantic_gate_precedes_test_and_never_touches_baseline() {
        let ir = compile("service Ping;\nrecord Msg { id: Uuid; }\napi Echo: Msg { method: POST; path: \"/echo\"; }\npipeline Echo: Return;\n");
        let gate = SemanticGate {
            source_file: "architecture/main.ciac",
            baseline: "architecture/.ciac/baselines/main.semantic.json",
        };
        let files = build(&ir, PYTHON_STEPS_FIXTURE, None, Some(gate));
        let (_, content) = &files[0];
        assert!(content.contains("  semantic-compat:\n"));
        assert!(content.contains("  test:\n    needs: semantic-compat\n"));
        // Job ordering: semantic-compat's block precedes test's.
        let gate_pos = content.find("semantic-compat:\n").unwrap();
        let test_pos = content.find("  test:\n").unwrap();
        assert!(gate_pos < test_pos);
        assert!(content.contains(
            "ciac diff architecture/main.ciac --semantic --deny-breaking --baseline architecture/.ciac/baselines/main.semantic.json --json"
        ));
        assert!(content.contains(&format!(
            "releases/download/v{}/ciac-linux-x86_64",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(!content.contains("baseline --update"));
        assert!(!content.contains("ciac baseline"));
    }

    #[test]
    fn multi_service_matrixes_image_build_and_polls_every_health_route() {
        let src = r#"
project MediaSystem;
record Video { id: Uuid; }
stream Uploaded: Video;

service Billing {
    api Charge: Video { method: POST; path: "/charge"; }
    pipeline Charge: Return;
}

service UploadApi {
    use { queue bus NATS; }
    api Upload: Video { method: PUT; path: "/videos"; }
    pipeline Upload: StoreVideo -> publish Uploaded -> Return;
}
"#;
        let ir = compile(src);
        let files = build(&ir, PYTHON_STEPS_FIXTURE, None, None);
        let (_, content) = &files[0];
        assert!(content.contains("strategy:"));
        assert!(content.contains("- billing"));
        assert!(content.contains("- upload-api"));
        assert!(content.contains("./${{ matrix.service }}"));
        assert!(content.contains("Wait for Billing's /health"));
        assert!(content.contains("Wait for UploadApi's /health"));
        assert!(content.contains("curl -sf http://localhost:8000/health"));
        assert!(content.contains("curl -sf http://localhost:8001/health"));
    }

    #[test]
    fn never_emits_real_credentials() {
        let ir = compile("service Ping;\nrecord Msg { id: Uuid; }\napi Echo: Msg { method: POST; path: \"/echo\"; }\npipeline Echo: Return;\n");
        let files = build(&ir, PYTHON_STEPS_FIXTURE, None, None);
        let (_, content) = &files[0];
        // Only the secrets.* references, never a literal value.
        assert!(content.contains("${{ secrets.REGISTRY_URL }}"));
        assert!(content.contains("${{ secrets.REGISTRY_USERNAME }}"));
        assert!(content.contains("${{ secrets.REGISTRY_PASSWORD }}"));
    }
}
