//! `--deploy terraform` (v0.11 M4): Terraform for the stateful
//! capabilities `--deploy k8s` deliberately refuses to provision.
//!
//! One `terraform/main.tf` per build, AWS as the single provider for
//! v0.11: an RDS instance per `db` (postgres or mysql engine), an
//! ElastiCache Redis cluster per `cache`, an MSK cluster when the
//! program uses `queue Kafka`, an S3 bucket per `object_store`.
//! Outputs surface connection values under the same env-var names the
//! compose file and k8s ConfigMap already use, so the three deployment
//! artifacts describe one system.
//!
//! Same discipline as `k8s.rs` (and stated in `docs/deployment.md`):
//! ciac proves the deployment *shape* — it emits the module, it does
//! not run `terraform apply`, manage state, or pick your VPC. Sizing
//! defaults follow the build's `--profile` (dev/staging/prod).

use crate::model::build_system;
use crate::{GenOptions, Profile};
use ciac_ir::NormalizedIr;

/// Builds `terraform/*.tf` for the program's stateful capability
/// instances. Empty when the program has none.
pub fn build(ir: &NormalizedIr, profile: Profile) -> Vec<(String, String)> {
    let system = build_system(ir, &GenOptions::default());
    let mut body = String::new();

    body.push_str(
        "# Generated by CIaC. Managed infrastructure for this system's\n\
         # stateful capabilities. Review sizing and networking before\n\
         # `terraform apply` -- ciac emits the shape, not your VPC.\n\n\
         terraform {\n\
         \x20 required_providers {\n\
         \x20   aws = {\n\
         \x20     source  = \"hashicorp/aws\"\n\
         \x20     version = \"~> 5.0\"\n\
         \x20   }\n\
         \x20 }\n\
         }\n\n\
         variable \"region\" {\n\
         \x20 type    = string\n\
         \x20 default = \"us-east-1\"\n\
         }\n\n\
         provider \"aws\" {\n\
         \x20 region = var.region\n\
         }\n",
    );

    let mut any = false;
    for ctx in &system.services {
        for inst in &ctx.db_instances {
            any = true;
            let engine = if inst.db_engine == "mysql" {
                "mysql"
            } else {
                "postgres"
            };
            let name = tf_name(&inst.container);
            body.push_str(&format!(
                "\nresource \"aws_db_instance\" \"{name}\" {{\n\
                 \x20 identifier          = \"{id}\"\n\
                 \x20 engine              = \"{engine}\"\n\
                 \x20 instance_class      = \"{class}\"\n\
                 \x20 allocated_storage   = {storage}\n\
                 \x20 db_name             = \"{db}\"\n\
                 \x20 username            = \"{user}\"\n\
                 \x20 manage_master_user_password = true\n\
                 \x20 skip_final_snapshot = {skip_final}\n\
                 }}\n\n\
                 output \"{env_lower}\" {{\n\
                 \x20 description = \"Connection host for {env}\"\n\
                 \x20 value       = aws_db_instance.{name}.address\n\
                 }}\n",
                name = name,
                id = inst.container,
                engine = engine,
                class = profile.db_instance_class(),
                storage = profile.db_storage_gb(),
                db = inst.db_name,
                user = inst.db_user,
                skip_final = profile.is_dev(),
                env_lower = inst.env_var.to_lowercase(),
                env = inst.env_var,
            ));
        }
        for inst in &ctx.cache_instances {
            any = true;
            let name = tf_name(&inst.container);
            body.push_str(&format!(
                "\nresource \"aws_elasticache_cluster\" \"{name}\" {{\n\
                 \x20 cluster_id      = \"{id}\"\n\
                 \x20 engine          = \"redis\"\n\
                 \x20 node_type       = \"{node}\"\n\
                 \x20 num_cache_nodes = 1\n\
                 }}\n\n\
                 output \"{env_lower}\" {{\n\
                 \x20 description = \"Connection host for {env}\"\n\
                 \x20 value       = aws_elasticache_cluster.{name}.cache_nodes[0].address\n\
                 }}\n",
                name = name,
                id = inst.container,
                node = profile.cache_node_type(),
                env_lower = inst.env_var.to_lowercase(),
                env = inst.env_var,
            ));
        }
        for inst in &ctx.object_store_instances {
            let Some(bucket) = &inst.bucket else { continue };
            any = true;
            let name = tf_name(&inst.snake);
            body.push_str(&format!(
                "\nresource \"aws_s3_bucket\" \"{name}\" {{\n\
                 \x20 bucket_prefix = \"{bucket}-\"\n\
                 }}\n",
            ));
        }
    }
    if system.queue_engine.as_deref() == Some("kafka") {
        any = true;
        body.push_str(&format!(
            "\nresource \"aws_msk_cluster\" \"queue\" {{\n\
             \x20 cluster_name           = \"{project}-queue\"\n\
             \x20 kafka_version          = \"3.6.0\"\n\
             \x20 number_of_broker_nodes = {brokers}\n\
             \x20 broker_node_group_info {{\n\
             \x20   instance_type   = \"{instance}\"\n\
             \x20   client_subnets  = var.queue_subnets\n\
             \x20   security_groups = var.queue_security_groups\n\
             \x20 }}\n\
             }}\n\n\
             variable \"queue_subnets\" {{\n\
             \x20 type = list(string)\n\
             }}\n\n\
             variable \"queue_security_groups\" {{\n\
             \x20 type = list(string)\n\
             }}\n\n\
             output \"kafka_url\" {{\n\
             \x20 description = \"Bootstrap brokers for KAFKA_URL\"\n\
             \x20 value       = aws_msk_cluster.queue.bootstrap_brokers\n\
             }}\n",
            project = system.project_name,
            brokers = profile.kafka_brokers(),
            instance = profile.kafka_instance_type(),
        ));
    }

    if !any && system.queue_engine.as_deref() != Some("kafka") {
        return Vec::new();
    }
    vec![("terraform/main.tf".to_owned(), body)]
}

/// Terraform resource labels can't contain `-`.
fn tf_name(container: &str) -> String {
    container.replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn compile(src: &str) -> NormalizedIr {
        let mut sources = ciac_diagnostics::SourceMap::new();
        let file = sources.add_file("test.ciac", src);
        let mut diags = ciac_diagnostics::Diagnostics::new();
        let program = ciac_syntax::parse(src, file, &mut diags);
        ciac_sema::analyze(&program, &mut diags)
            .unwrap_or_else(|| panic!("compiles: {:?}", diags.codes()))
    }

    #[test]
    fn stateful_capabilities_get_aws_resources_with_matching_outputs() {
        let ir = compile(
            "service Notes;\nuse { db Postgres; cache Redis; }\nrecord Note { id: Uuid; title: String; }\ncrud Note: Note;\n",
        );
        let files = build(&ir, Profile::Dev);
        assert_eq!(files.len(), 1);
        let (path, tf) = &files[0];
        assert_eq!(path, "terraform/main.tf");
        assert!(tf.contains("aws_db_instance"), "{tf}");
        assert!(tf.contains("engine              = \"postgres\""), "{tf}");
        assert!(tf.contains("aws_elasticache_cluster"), "{tf}");
        // Outputs use the same env-var names compose/k8s already use.
        assert!(tf.contains("output \"database_url\""), "{tf}");
        assert!(tf.contains("output \"redis_url\""), "{tf}");
    }

    #[test]
    fn mysql_instances_use_the_mysql_engine() {
        let ir = compile(
            "service Notes;\nuse { db MySQL; }\nrecord Note { id: Uuid; title: String; }\ncrud Note: Note;\n",
        );
        let (_, tf) = &build(&ir, Profile::Prod)[0];
        assert!(tf.contains("engine              = \"mysql\""), "{tf}");
        // Prod sizing differs from dev.
        assert!(tf.contains(Profile::Prod.db_instance_class()), "{tf}");
    }

    #[test]
    fn kafka_queue_gets_an_msk_cluster() {
        let ir = compile(
            "service X;\nuse { queue Kafka; }\nrecord E { id: Uuid; }\nstream S: E;\napi In: E;\nworker W on S;\npipeline In: publish S -> Return;\npipeline W: Work;\n",
        );
        let (_, tf) = &build(&ir, Profile::Dev)[0];
        assert!(tf.contains("aws_msk_cluster"), "{tf}");
        assert!(tf.contains("output \"kafka_url\""), "{tf}");
    }

    #[test]
    fn capability_free_programs_emit_nothing() {
        let ir = compile(
            "service Ping;\nrecord M { id: Uuid; }\napi Echo: M { method: POST; path: \"/e\"; }\npipeline Echo: Return;\n",
        );
        assert!(build(&ir, Profile::Dev).is_empty());
    }
}
