//! TypeScript client generation (v0.15 M2): `--client ts`.
//!
//! A dependency-free typed `fetch` client package generated straight
//! from the IR (via the same [`crate::model`] every backend renders
//! from) — not shelled out to an external OpenAPI-generator process.
//! This keeps the client deterministic and golden-coverable like
//! everything else `ciac build` emits, and is deliberately the
//! smallest TypeScript artifact worth shipping: it serves the
//! TS-consumer audience today and proves the record→TS type mapping
//! that a full TypeScript backend (tracked separately) would need
//! anyway.
//!
//! One package covers the whole build, single- or multi-service:
//! multi-service function names are prefixed with the owning
//! service's name to avoid collisions, since two services can (and in
//! practice do) declare routes with the same local name.

use crate::model::{
    ApiCtx, Ctx, EnumCtx, FieldCtx, FieldTypeKind, RecordCtx, ResourceCtx, SystemModel,
};
use heck::{ToLowerCamelCase, ToPascalCase};
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// Builds the whole `clients/ts/` package: `(path, content)` pairs
/// relative to the generated project root.
pub fn build(system: &SystemModel) -> Vec<(String, String)> {
    let mut type_blocks: BTreeMap<String, String> = BTreeMap::new();
    for ctx in &system.services {
        for record in &ctx.records {
            type_blocks
                .entry(record.name.clone())
                .or_insert_with(|| record_interface(record));
            for e in &record.enums {
                type_blocks
                    .entry(e.name.clone())
                    .or_insert_with(|| enum_type(e));
            }
        }
        for resource in &ctx.resources {
            let (in_iface, out_iface) = resource_interfaces(resource);
            type_blocks
                .entry(format!("{}In", resource.name))
                .or_insert(in_iface);
            type_blocks
                .entry(format!("{}Out", resource.name))
                .or_insert(out_iface);
            if let Some(record) = &resource.record {
                for e in &record.enums {
                    type_blocks
                        .entry(e.name.clone())
                        .or_insert_with(|| enum_type(e));
                }
            }
        }
    }

    let mut types = String::new();
    types.push_str(
        "// Generated by CIaC. Record and CRUD schemas from the program's IR.\n\n\
         /** Every `api` route wraps its pipeline's result in this envelope. */\n\
         export interface Envelope<T> {\n  status: string;\n  data: T;\n}\n\n",
    );
    for block in type_blocks.values() {
        types.push_str(block);
        types.push('\n');
    }

    let mut client = String::new();
    client.push_str(CLIENT_PRELUDE);
    for ctx in &system.services {
        write_service_functions(&mut client, ctx, system.multi);
    }

    vec![
        (
            "clients/ts/package.json".to_owned(),
            package_json(&system.project_name),
        ),
        ("clients/ts/tsconfig.json".to_owned(), TSCONFIG.to_owned()),
        ("clients/ts/src/types.ts".to_owned(), types),
        ("clients/ts/src/client.ts".to_owned(), client),
        (
            "clients/ts/src/index.ts".to_owned(),
            "export * from \"./types\";\nexport * from \"./client\";\n".to_owned(),
        ),
        ("clients/ts/README.md".to_owned(), README.to_owned()),
    ]
}

const CLIENT_PRELUDE: &str = r#"// Generated by CIaC. One function per route; scope-bearing routes
// require `AuthenticatedClientOptions` so a missing token is a
// compile error, not a 401 at runtime.
import type * as Types from "./types";

export interface ClientOptions {
  baseUrl: string;
}

export interface AuthenticatedClientOptions extends ClientOptions {
  token: string;
}

function authHeader(opts: ClientOptions): Record<string, string> {
  const token = (opts as Partial<AuthenticatedClientOptions>).token;
  return token ? { Authorization: `Bearer ${token}` } : {};
}

async function request<T>(
  opts: ClientOptions,
  path: string,
  method: string,
  body?: unknown,
): Promise<T> {
  const headers: Record<string, string> = { ...authHeader(opts) };
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
  }
  const res = await fetch(`${opts.baseUrl}${path}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`${method} ${path} failed: ${res.status}`);
  }
  if (res.status === 204) {
    return undefined as T;
  }
  return (await res.json()) as T;
}

"#;

fn ts_scalar(kind: &FieldTypeKind) -> String {
    match kind {
        FieldTypeKind::Str | FieldTypeKind::Uuid | FieldTypeKind::Timestamp => "string".to_owned(),
        FieldTypeKind::Int | FieldTypeKind::Float => "number".to_owned(),
        FieldTypeKind::Bool => "boolean".to_owned(),
        FieldTypeKind::Json => "Record<string, unknown>".to_owned(),
        FieldTypeKind::Enum { name, .. } => name.clone(),
        // v0.16 M4: a to-one reference is a plain id on the wire (see
        // `FieldTypeKind::Reference`'s own doc comment) — same TS shape
        // as `Uuid`. `interface_body` below adds the doc comment naming
        // which record it targets.
        FieldTypeKind::Reference { .. } => "string".to_owned(),
    }
}

fn interface_body<'a>(fields: impl IntoIterator<Item = &'a FieldCtx>) -> String {
    let mut body = String::new();
    for field in fields {
        if let FieldTypeKind::Reference { target_record, .. } = &field.type_kind {
            let _ = writeln!(body, "  /** References `{target_record}` by id. */");
        }
        let _ = writeln!(body, "  {}: {};", field.name, ts_scalar(&field.type_kind));
    }
    body
}

fn record_interface(record: &RecordCtx) -> String {
    format!(
        "export interface {} {{\n{}}}\n",
        record.name,
        interface_body(&record.fields)
    )
}

fn enum_type(e: &EnumCtx) -> String {
    let variants = e
        .variants
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" | ");
    format!("export type {} = {};\n", e.name, variants)
}

/// The `{Name}In`/`{Name}Out` pair a CRUD resource exposes: typed
/// columns from the bound record (`In` drops `id`), or the generic
/// `id`+`data` document shape when the resource has no record — same
/// split `models.py.j2`/`ciac_codegen::openapi` already make.
fn resource_interfaces(resource: &ResourceCtx) -> (String, String) {
    match &resource.record {
        Some(record) => {
            let non_id: Vec<&FieldCtx> = record.fields.iter().filter(|f| f.name != "id").collect();
            let in_iface = format!(
                "export interface {}In {{\n{}}}\n",
                resource.name,
                interface_body(non_id.iter().copied())
            );
            let mut out_body = String::from("  id: string;\n");
            out_body.push_str(&interface_body(non_id));
            let out_iface = format!("export interface {}Out {{\n{}}}\n", resource.name, out_body);
            (in_iface, out_iface)
        }
        None => (
            format!(
                "export interface {}In {{\n  data: Record<string, unknown>;\n}}\n",
                resource.name
            ),
            format!(
                "export interface {}Out {{\n  id: string;\n  data: Record<string, unknown>;\n}}\n",
                resource.name
            ),
        ),
    }
}

fn opts_type(requires_auth: bool) -> &'static str {
    if requires_auth {
        "AuthenticatedClientOptions"
    } else {
        "ClientOptions"
    }
}

/// Function name for one `api`/CRUD operation: bare in a single-service
/// build, service-prefixed (`billingCharge`) in a multi-service one so
/// two services' same-named routes don't collide in one flat module.
fn fn_name(ctx: &Ctx, multi: bool, base: &str) -> String {
    if multi {
        format!(
            "{}{}",
            ctx.module.to_lower_camel_case(),
            base.to_pascal_case()
        )
    } else {
        base.to_lower_camel_case()
    }
}

fn write_service_functions(out: &mut String, ctx: &Ctx, multi: bool) {
    for api in &ctx.apis {
        write_api_function(out, ctx, api, multi);
    }
    for resource in &ctx.resources {
        write_resource_functions(out, ctx, resource, multi);
    }
}

fn write_api_function(out: &mut String, ctx: &Ctx, api: &ApiCtx, multi: bool) {
    let name = fn_name(ctx, multi, &api.snake);
    let opts_ty = opts_type(api.has_auth_step);
    let data_ty = api
        .payload
        .as_ref()
        .map(|p| format!("Types.{}", p.class_name))
        .unwrap_or_else(|| "Record<string, unknown>".to_owned());
    let response_ty = format!("Types.Envelope<{data_ty}>");
    if api.has_body {
        let payload_ty = api
            .payload
            .as_ref()
            .map(|p| format!("Types.{}", p.class_name))
            .unwrap_or_else(|| "unknown".to_owned());
        let _ = writeln!(
            out,
            "export async function {name}(opts: {opts_ty}, payload: {payload_ty}): Promise<{response_ty}> {{\n  \
             return request(opts, {route:?}, \"{method}\", payload);\n}}\n",
            route = api.route,
            method = api.method_upper,
        );
    } else {
        let _ = writeln!(
            out,
            "export async function {name}(opts: {opts_ty}): Promise<{response_ty}> {{\n  \
             return request(opts, {route:?}, \"{method}\");\n}}\n",
            route = api.route,
            method = api.method_upper,
        );
    }
}

fn write_resource_functions(out: &mut String, ctx: &Ctx, resource: &ResourceCtx, multi: bool) {
    let base = format!("/{}", resource.plural);
    let by_id = format!("{base}/{{}}");
    let in_ty = format!("Types.{}In", resource.name);
    let out_ty = format!("Types.{}Out", resource.name);
    let create_opts = opts_type(resource.has_auth);
    let read_opts = opts_type(resource.has_auth);

    let create_name = fn_name(ctx, multi, &format!("create_{}", resource.snake));
    let _ = writeln!(
        out,
        "export async function {create_name}(opts: {create_opts}, payload: {in_ty}): Promise<{out_ty}> {{\n  \
         return request(opts, {base:?}, \"POST\", payload);\n}}\n",
    );

    let list_name = fn_name(ctx, multi, &format!("list_{}", resource.plural));
    let _ = writeln!(
        out,
        "export async function {list_name}(opts: {read_opts}, params?: {{ limit?: number; offset?: number }}): Promise<{out_ty}[]> {{\n  \
         const q = new URLSearchParams();\n  \
         if (params?.limit !== undefined) q.set(\"limit\", String(params.limit));\n  \
         if (params?.offset !== undefined) q.set(\"offset\", String(params.offset));\n  \
         const qs = q.toString();\n  \
         return request(opts, qs ? `{base}?${{qs}}` : {base:?}, \"GET\");\n}}\n",
    );

    let get_name = fn_name(ctx, multi, &format!("get_{}", resource.snake));
    let _ = writeln!(
        out,
        "export async function {get_name}(opts: {read_opts}, id: string): Promise<{out_ty}> {{\n  \
         return request(opts, `{by_id_fmt}`.replace(\"{{}}\", encodeURIComponent(id)), \"GET\");\n}}\n",
        by_id_fmt = by_id,
    );

    let update_name = fn_name(ctx, multi, &format!("update_{}", resource.snake));
    let _ = writeln!(
        out,
        "export async function {update_name}(opts: {create_opts}, id: string, payload: {in_ty}): Promise<{out_ty}> {{\n  \
         return request(opts, `{by_id_fmt}`.replace(\"{{}}\", encodeURIComponent(id)), \"PUT\", payload);\n}}\n",
        by_id_fmt = by_id,
    );

    let delete_name = fn_name(ctx, multi, &format!("delete_{}", resource.snake));
    let _ = writeln!(
        out,
        "export async function {delete_name}(opts: {create_opts}, id: string): Promise<void> {{\n  \
         return request(opts, `{by_id_fmt}`.replace(\"{{}}\", encodeURIComponent(id)), \"DELETE\");\n}}\n",
        by_id_fmt = by_id,
    );
}

fn package_json(project_name: &str) -> String {
    format!(
        r#"{{
  "name": "{project_name}-client",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "main": "src/index.ts",
  "types": "src/index.ts",
  "scripts": {{
    "typecheck": "tsc --noEmit"
  }},
  "devDependencies": {{
    "typescript": "^5.4.0"
  }}
}}
"#
    )
}

const TSCONFIG: &str = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "lib": ["ES2020", "DOM"]
  },
  "include": ["src"]
}
"#;

const README: &str = r#"# Generated TypeScript client

Dependency-free (uses the global `fetch`) — generated by `ciac build
--client ts` straight from the program's IR, the same source every
backend renders from. Routes that require auth take
`AuthenticatedClientOptions` instead of `ClientOptions`, so a missing
token is a compile error rather than a 401 at runtime.

```ts
import { createNote, type NoteIn } from "./src";

const opts = { baseUrl: "http://localhost:8000", token: "..." };
const note = await createNote(opts, { title: "hi" } satisfies NoteIn);
```

Run `npm run typecheck` (after `npm install`) to type-check the
package on its own.
"#;
