//! v0.15 M6: the `users Keycloak` dev identity provider.
//!
//! `use { users Keycloak; }` makes an OAuth2-shaped system runnable
//! without an external IdP: compose gains a Keycloak container seeded
//! (via `--import-realm`) with a `dev` realm, a public client
//! (`ciac-dev`, password grant enabled), one client scope per scope
//! string declared anywhere in the system, and two dev users. `auth
//! OAuth2`'s `issuer` defaults to this container's URL
//! (`model::KEYCLOAK_DEV_ISSUER`) when the program's own `use { .. }`
//! block omits one (`ciac-sema::build`'s `("auth", Some("OAuth2"))`
//! arm) -- explicit `issuer` still wins.
//!
//! Disclosed simplification: Keycloak authorizes *optional* client
//! scopes per client, not per user, so `scripts/token.sh` -- not the
//! realm -- is what makes `dev-admin` a "has every scope" identity and
//! `dev-user` a "has none" one, by choosing which scopes to request at
//! token time. That's an honest fit for a dev/test identity provider
//! (the resource-server stance from v0.11 M2 stands: no user CRUD, no
//! registration/login UI, no session management), not a production
//! authorization model.
//!
//! Like `ci.rs` (v0.15 M5), this is plain Rust string/JSON building
//! rather than a minijinja template: the realm and script are
//! backend-agnostic, driven only by the system's declared scopes.

use crate::model::SystemModel;
use serde_json::{json, Value};

/// `keycloak-realm.json`, mounted into the container's
/// `/opt/keycloak/data/import/` directory (v0.15 M6). Same file
/// regardless of single-/multi-service layout, so callers pass the
/// already-unioned [`SystemModel::all_scopes`].
pub fn realm_json(all_scopes: &[String]) -> String {
    let client_scopes: Vec<Value> = all_scopes
        .iter()
        .map(|scope| {
            json!({
                "name": scope,
                "protocol": "openid-connect",
                "attributes": {
                    "include.in.token.scope": "true",
                    "display.on.consent.screen": "false",
                },
            })
        })
        .collect();
    let realm = json!({
        "realm": "dev",
        "enabled": true,
        "sslRequired": "none",
        "registrationAllowed": false,
        "clients": [{
            "clientId": "ciac-dev",
            "enabled": true,
            "publicClient": true,
            "directAccessGrantsEnabled": true,
            "standardFlowEnabled": false,
            "protocol": "openid-connect",
            "redirectUris": ["*"],
            "optionalClientScopes": all_scopes,
        }],
        "clientScopes": client_scopes,
        "users": [
            {
                "username": "dev-admin",
                "enabled": true,
                "emailVerified": true,
                "credentials": [{"type": "password", "value": "dev-password", "temporary": false}],
            },
            {
                "username": "dev-user",
                "enabled": true,
                "emailVerified": true,
                "credentials": [{"type": "password", "value": "dev-password", "temporary": false}],
            },
        ],
    });
    serde_json::to_string_pretty(&realm).expect("realm JSON serializes") + "\n"
}

/// `scripts/token.sh`: mints a real access token from the dev realm
/// via the resource-owner-password-credentials grant, for humans and
/// for the generated `tests/system/` suite to present real bearer
/// tokens instead of hand-signed JWTs (only possible for the `jwt`
/// scheme -- see `ciac-backend-*`'s `scope_tests.rs.j2`/
/// `test_smoke.py.j2`, which need a live issuer for `oauth2`).
/// dependency-free: `curl` + `sed`, no `jq`/`python3` requirement.
pub fn token_script(all_scopes: &[String]) -> String {
    let admin_scope = all_scopes.join(" ");
    format!(
        "#!/usr/bin/env bash\n\
         # Mints a real OAuth2 access token from the dev Keycloak realm\n\
         # (v0.15 M6). Generated by CIaC.\n\
         #\n\
         # Usage: scripts/token.sh <dev-admin|dev-user> [scope ...]\n\
         #   scripts/token.sh dev-admin{admin_scope_usage}\n\
         #   scripts/token.sh dev-user\n\
         set -euo pipefail\n\
         \n\
         KEYCLOAK_URL=\"${{KEYCLOAK_URL:-http://localhost:8080}}\"\n\
         REALM=\"dev\"\n\
         CLIENT_ID=\"ciac-dev\"\n\
         PASSWORD=\"dev-password\"\n\
         \n\
         USER=\"${{1:?usage: scripts/token.sh <dev-admin|dev-user> [scope ...]}}\"\n\
         shift || true\n\
         SCOPE=\"$*\"\n\
         \n\
         args=(-d \"client_id=$CLIENT_ID\" -d \"grant_type=password\" -d \"username=$USER\" -d \"password=$PASSWORD\")\n\
         if [ -n \"$SCOPE\" ]; then\n\
         \x20\x20args+=(-d \"scope=$SCOPE\")\n\
         fi\n\
         \n\
         response=\"$(curl -sf \"${{args[@]}}\" \"$KEYCLOAK_URL/realms/$REALM/protocol/openid-connect/token\")\"\n\
         if command -v jq >/dev/null 2>&1; then\n\
         \x20\x20printf '%s\\n' \"$response\" | jq -r .access_token\n\
         else\n\
         \x20\x20printf '%s\\n' \"$response\" | sed -n 's/.*\"access_token\":\"\\([^\"]*\\)\".*/\\1/p'\n\
         fi\n",
        admin_scope_usage = if admin_scope.is_empty() {
            String::new()
        } else {
            format!(" \"{admin_scope}\"")
        },
    )
}

/// Files this capability contributes to the generated project tree,
/// gated on [`SystemModel::has_users`] by each backend's `lib.rs`
/// (the same call site that adds `otel-collector-config.yaml` for
/// `has_tracing`, v0.15 M3/M4).
pub fn build(model: &SystemModel) -> Vec<(String, String)> {
    vec![
        (
            "keycloak-realm.json".to_owned(),
            realm_json(&model.all_scopes),
        ),
        (
            "scripts/token.sh".to_owned(),
            token_script(&model.all_scopes),
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn realm_json_is_valid_json_and_carries_every_scope() {
        let scopes = vec!["orders:read".to_owned(), "orders:write".to_owned()];
        let text = realm_json(&scopes);
        let value: Value = serde_json::from_str(&text).expect("valid JSON");
        assert_eq!(value["realm"], "dev");
        assert_eq!(value["clients"][0]["clientId"], "ciac-dev");
        assert_eq!(value["clients"][0]["directAccessGrantsEnabled"], true);
        let scope_names: Vec<&str> = value["clientScopes"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| s["name"].as_str().unwrap())
            .collect();
        assert_eq!(scope_names, ["orders:read", "orders:write"]);
        let usernames: Vec<&str> = value["users"]
            .as_array()
            .unwrap()
            .iter()
            .map(|u| u["username"].as_str().unwrap())
            .collect();
        assert_eq!(usernames, ["dev-admin", "dev-user"]);
    }

    #[test]
    fn realm_json_with_no_scopes_is_still_valid() {
        let text = realm_json(&[]);
        let value: Value = serde_json::from_str(&text).expect("valid JSON");
        assert_eq!(value["clientScopes"].as_array().unwrap().len(), 0);
    }

    #[test]
    fn token_script_never_hardcodes_a_real_secret() {
        let script = token_script(&["orders:read".to_owned()]);
        assert!(script.contains("PASSWORD=\"dev-password\""));
        assert!(script.contains("client_id=$CLIENT_ID"));
        assert!(script.contains("grant_type=password"));
        assert!(script.contains("/realms/$REALM/protocol/openid-connect/token"));
    }
}
