// Command ciac-backend-go is a real, standalone external backend for
// ciac (https://github.com/jrcalgo/ciac) — v0.8 external-backend
// protocol M3. It has no dependency on the ciac Rust workspace at
// all: it speaks CodegenRequest/CodegenResponse (as defined by
// crates/ciac-codegen/src/protocol.rs) as plain JSON on stdin/stdout,
// exactly as ciac_codegen::external::ExternalBackend invokes any
// `ciac-backend-<target>` executable found on $PATH.
//
// Scope is deliberately the same narrow slice the v0.8 M6 Go backend
// spike used (docs/backend-spike-report.md in the ciac repo): one
// service, one record, one api, no capabilities. Anything wider
// (auth, db, cache, queue, object store, email, search, external
// HTTP, or typed handlers) is refused loudly on stderr with a
// non-zero exit rather than attempted — the "attempt everything, fail
// loudly" contract ExternalBackend already assumes of every external
// target.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"strings"
	"unicode"
)

const protocolVersion = 1

// Only the fields this backend actually reads are declared here —
// encoding/json ignores everything else in the request, so this is
// deliberately a partial mirror of SystemModel/Ctx, not a full one.

type fieldCtx struct {
	Name     string `json:"name"`
	RustType string `json:"rust_type"`
}

type recordCtx struct {
	Name   string     `json:"name"`
	Fields []fieldCtx `json:"fields"`
}

type payloadRef struct {
	ClassName string `json:"class_name"`
}

type apiCtx struct {
	Name        string      `json:"name"`
	Route       string      `json:"route"`
	MethodUpper string      `json:"method_upper"`
	HasBody     bool        `json:"has_body"`
	Payload     *payloadRef `json:"payload"`
}

type serviceCtx struct {
	ServiceName     string            `json:"service_name"`
	Package         string            `json:"package"`
	HostPort        int               `json:"host_port"`
	HasAuth         bool              `json:"has_auth"`
	HasDB           bool              `json:"has_db"`
	HasCache        bool              `json:"has_cache"`
	HasQueue        bool              `json:"has_queue"`
	HasObjectStore  bool              `json:"has_object_store"`
	HasEmail        bool              `json:"has_email"`
	HasSearch       bool              `json:"has_search"`
	HasExternalHTTP bool              `json:"has_external_http"`
	Records         []recordCtx       `json:"records"`
	Apis            []apiCtx          `json:"apis"`
	TypedHandlers   []json.RawMessage `json:"typed_handlers"`
}

type systemModel struct {
	ProjectName string       `json:"project_name"`
	Services    []serviceCtx `json:"services"`
}

type codegenRequest struct {
	ProtocolVersion uint32      `json:"protocol_version"`
	Target          string      `json:"target"`
	System          systemModel `json:"system"`
}

type responseFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
	Role    string `json:"role"`
}

type codegenResponse struct {
	ProtocolVersion uint32         `json:"protocol_version"`
	Files           []responseFile `json:"files"`
	Notes           []string       `json:"notes"`
}

func main() {
	if err := run(os.Stdin, os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "ciac-backend-go: %s\n", err)
		os.Exit(1)
	}
}

func run(in io.Reader, out io.Writer) error {
	input, err := io.ReadAll(in)
	if err != nil {
		return fmt.Errorf("reading request from stdin: %w", err)
	}

	var req codegenRequest
	if err := json.Unmarshal(input, &req); err != nil {
		return fmt.Errorf("decoding request: %w", err)
	}
	if req.ProtocolVersion != protocolVersion {
		return fmt.Errorf(
			"speaks protocol version %d, but the request wants version %d",
			protocolVersion, req.ProtocolVersion,
		)
	}
	if len(req.System.Services) != 1 {
		return fmt.Errorf(
			"only single-service programs are supported (api + record only, no capabilities); got %d services",
			len(req.System.Services),
		)
	}

	svc := req.System.Services[0]
	if reason := unsupportedReason(svc); reason != "" {
		return fmt.Errorf(
			"service %q needs %s, which this backend does not support (api + record only, no capabilities)",
			svc.ServiceName, reason,
		)
	}

	mainGo, err := renderMainGo(svc)
	if err != nil {
		return fmt.Errorf("rendering main.go: %w", err)
	}

	resp := codegenResponse{
		ProtocolVersion: protocolVersion,
		Files: []responseFile{
			{Path: "go.mod", Content: renderGoMod(svc.Package), Role: "owned"},
			{Path: "main.go", Content: mainGo, Role: "owned"},
		},
		Notes: []string{fmt.Sprintf("generated by ciac-backend-go for service %s", svc.ServiceName)},
	}

	encoded, err := json.Marshal(resp)
	if err != nil {
		return fmt.Errorf("encoding response: %w", err)
	}
	_, err = out.Write(encoded)
	return err
}

// unsupportedReason reports the first capability this narrow backend
// can't handle, or "" if svc is within scope (api + record only).
func unsupportedReason(svc serviceCtx) string {
	switch {
	case svc.HasAuth:
		return "auth"
	case svc.HasDB:
		return "a database"
	case svc.HasCache:
		return "a cache"
	case svc.HasQueue:
		return "a queue"
	case svc.HasObjectStore:
		return "an object store"
	case svc.HasEmail:
		return "email"
	case svc.HasSearch:
		return "search"
	case svc.HasExternalHTTP:
		return "external HTTP calls"
	case len(svc.TypedHandlers) > 0:
		return "typed handlers"
	default:
		return ""
	}
}

func renderGoMod(pkg string) string {
	if pkg == "" {
		pkg = "ciacgen"
	}
	return fmt.Sprintf("module %s\n\ngo 1.21\n", pkg)
}

func renderMainGo(svc serviceCtx) (string, error) {
	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString(")\n\n")

	for _, rec := range svc.Records {
		writeStruct(&b, rec)
	}

	for _, api := range svc.Apis {
		writeHandler(&b, api)
	}

	b.WriteString("func healthHandler(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\tjson.NewEncoder(w).Encode(map[string]string{\"status\": \"ok\"})\n")
	b.WriteString("}\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\thttp.HandleFunc(\"/health\", healthHandler)\n")
	for _, api := range svc.Apis {
		fmt.Fprintf(&b, "\thttp.HandleFunc(%q, %s)\n", api.Route, handlerFuncName(api))
	}
	port := svc.HostPort
	if port == 0 {
		port = 8000
	}
	fmt.Fprintf(&b, "\taddr := \":%d\"\n", port)
	fmt.Fprintf(&b, "\tlog.Printf(%q, addr)\n", "listening on %s")
	b.WriteString("\tif err := http.ListenAndServe(addr, nil); err != nil {\n")
	b.WriteString("\t\tlog.Fatal(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		// Surfacing the unformatted source alongside the error makes a
		// codegen bug in this function diagnosable without rerunning
		// with a debugger attached.
		return "", fmt.Errorf("%w (generated source:\n%s)", err, b.String())
	}
	return string(formatted), nil
}

func writeStruct(b *strings.Builder, rec recordCtx) {
	fmt.Fprintf(b, "type %s struct {\n", exportedName(rec.Name))
	for _, f := range rec.Fields {
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", exportedName(f.Name), goType(f.RustType), f.Name)
	}
	b.WriteString("}\n\n")
}

func writeHandler(b *strings.Builder, api apiCtx) {
	fmt.Fprintf(b, "func %s(w http.ResponseWriter, r *http.Request) {\n", handlerFuncName(api))
	fmt.Fprintf(b, "\tif r.Method != %q {\n", api.MethodUpper)
	b.WriteString("\t\thttp.Error(w, \"method not allowed\", http.StatusMethodNotAllowed)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	if api.HasBody && api.Payload != nil {
		typeName := exportedName(api.Payload.ClassName)
		fmt.Fprintf(b, "\tvar payload %s\n", typeName)
		b.WriteString("\tif err := json.NewDecoder(r.Body).Decode(&payload); err != nil {\n")
		b.WriteString("\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		b.WriteString("\tjson.NewEncoder(w).Encode(map[string]interface{}{\"data\": payload, \"status\": \"accepted\"})\n")
	} else {
		b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		b.WriteString("\tjson.NewEncoder(w).Encode(map[string]string{\"status\": \"accepted\"})\n")
	}
	b.WriteString("}\n\n")
}

func handlerFuncName(api apiCtx) string {
	return unexportedName(api.Name) + "Handler"
}

// goType maps a field's Rust type (the closest thing FieldCtx offers
// to a language-neutral type) onto a Go type. FieldCtx
// (ciac-codegen/src/model.rs) has no generic type-mapping hook and no
// go_type field — the same gap the v0.8 M6 Go spike already found and
// hand-translated around (docs/backend-spike-report.md); this is that
// same workaround, not a fix to FieldCtx itself.
func goType(rustType string) string {
	switch rustType {
	case "String":
		return "string"
	case "i64":
		return "int64"
	case "f64":
		return "float64"
	case "bool":
		return "bool"
	case "chrono::DateTime<chrono::Utc>":
		// Kept as the RFC3339 string the JSON wire format already
		// uses rather than pulling in time.Time's own JSON quirks.
		return "string"
	case "serde_json::Value":
		return "interface{}"
	default:
		// Most likely an enum's generated Rust type name (e.g.
		// "VideoStatus") -- falls back to string, same as the spike.
		return "string"
	}
}

func exportedName(name string) string {
	if name == "" {
		return name
	}
	r := []rune(name)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func unexportedName(name string) string {
	if name == "" {
		return name
	}
	r := []rune(name)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
