//! Python (FastAPI ecosystem) code-generation backend.
//!
//! Maps the CIaC ontology onto production-standard Python components:
//!
//! | CIaC          | Python                                  |
//! |---------------|-----------------------------------------|
//! | API           | FastAPI `APIRouter`                     |
//! | Service       | plain async service class               |
//! | Worker        | NATS subscription in an asyncio task    |
//! | Database      | SQLAlchemy (async) + asyncpg            |
//! | Cache         | redis-py (asyncio)                      |
//! | Queue         | nats-py                                 |
//! | Auth (JWT)    | FastAPI dependency + PyJWT              |
//! | Logging       | structlog                               |
//! | Metrics       | prometheus-client `/metrics` endpoint   |
//!
//! The generated project is import-safe without any infrastructure
//! running: database, cache, and queue clients are created lazily, so the
//! generated smoke tests pass on a bare checkout.

use ciac_codegen::model as context;
use ciac_codegen::{Backend, BackendError, GenOptions, GeneratedProject};
use ciac_ir::{Component, NormalizedIr};
use include_dir::{include_dir, Dir};
use minijinja::context;

static TEMPLATES: Dir = include_dir!("$CARGO_MANIFEST_DIR/templates");

#[derive(Debug, Default)]
pub struct PythonBackend;

impl Backend for PythonBackend {
    fn id(&self) -> &'static str {
        "python"
    }

    fn description(&self) -> &'static str {
        "Python 3.11+ project using FastAPI, SQLAlchemy, redis-py, and nats-py"
    }

    fn supports(&self, component: &Component) -> bool {
        // Kafka has no generator yet; everything else is implemented.
        !matches!(
            component,
            Component::Queue {
                engine: ciac_ir::QueueEngine::Kafka,
                ..
            }
        )
    }

    fn generate(
        &self,
        ir: &NormalizedIr,
        opts: &GenOptions,
    ) -> Result<GeneratedProject, BackendError> {
        let ctx = context::build(ir, opts);
        let env = ciac_codegen::template::environment(TEMPLATES.files().map(|f| {
            (
                f.path().to_str().expect("template names are utf-8"),
                f.contents_utf8().expect("templates are utf-8"),
            )
        }))?;
        let base = minijinja::Value::from_serialize(&ctx);
        let render = |name: &str, extra: minijinja::Value| -> Result<String, BackendError> {
            Ok(env
                .get_template(name)?
                .render(context! { c => base, ..extra })?)
        };

        let mut project = GeneratedProject::new();
        let empty = || context! {};

        project.add_file("pyproject.toml", render("pyproject.toml.j2", empty())?);
        project.add_file("README.md", render("README.md.j2", empty())?);
        project.add_file("Dockerfile", render("Dockerfile.j2", empty())?);
        project.add_file(
            "docker-compose.yml",
            render("docker-compose.yml.j2", empty())?,
        );
        project.add_file("conftest.py", render("conftest.py.j2", empty())?);
        project.add_file(
            "app/__init__.py",
            format!(
                "\"\"\"{} — generated by CIaC. Structure is compiler-owned;\nbusiness logic belongs in `app/services/`.\"\"\"\n",
                ctx.service_name
            ),
        );
        project.add_file("app/main.py", render("main.py.j2", empty())?);
        project.add_file("app/config.py", render("config.py.j2", empty())?);
        if ctx.has_auth {
            project.add_file("app/auth.py", render("auth.py.j2", empty())?);
        }
        if ctx.has_db {
            project.add_file("app/db.py", render("db.py.j2", empty())?);
        }
        if ctx.has_cache {
            project.add_file("app/cache.py", render("cache.py.j2", empty())?);
        }
        if ctx.has_queue {
            project.add_file("app/queue.py", render("queue.py.j2", empty())?);
        }
        if ctx.has_logging || ctx.has_metrics {
            project.add_file(
                "app/observability.py",
                render("observability.py.j2", empty())?,
            );
        }
        if !ctx.records.is_empty() {
            project.add_file("app/schemas.py", render("schemas.py.j2", empty())?);
        }
        if !ctx.resources.is_empty() {
            project.add_file("app/models.py", render("models.py.j2", empty())?);
        }

        if !ctx.apis.is_empty() || !ctx.resources.is_empty() {
            project.add_file("app/api/__init__.py", "\"\"\"HTTP routers.\"\"\"\n");
        }
        for api in &ctx.apis {
            project.add_file(
                format!("app/api/{}.py", api.snake),
                render("api.py.j2", context! { api => api })?,
            );
        }
        for resource in &ctx.resources {
            project.add_file(
                format!("app/api/{}.py", resource.snake),
                render("resource_api.py.j2", context! { resource => resource })?,
            );
        }

        if !ctx.services.is_empty() || !ctx.resources.is_empty() {
            project.add_file(
                "app/services/__init__.py",
                "\"\"\"Business-logic handlers. This is where your code goes.\"\"\"\n",
            );
        }
        for service in &ctx.services {
            project.add_file(
                format!("app/services/{}.py", service.module),
                render("service.py.j2", context! { service => service })?,
            );
        }
        for resource in &ctx.resources {
            project.add_file(
                format!("app/services/{}.py", resource.store_module),
                render("resource_store.py.j2", context! { resource => resource })?,
            );
        }

        if !ctx.workers.is_empty() || !ctx.consumers.is_empty() {
            project.add_file(
                "app/workers/__init__.py",
                "\"\"\"Queue-driven workers. Run them all with `python -m app.workers`.\"\"\"\n",
            );
            project.add_file(
                "app/workers/__main__.py",
                render("workers_main.py.j2", empty())?,
            );
        }
        for worker in &ctx.workers {
            project.add_file(
                format!("app/workers/{}.py", worker.snake),
                render("worker.py.j2", context! { worker => worker })?,
            );
        }
        for consumer in &ctx.consumers {
            project.add_file(
                format!("app/workers/{}.py", consumer.snake),
                render("consumer.py.j2", context! { consumer => consumer })?,
            );
        }

        project.add_file("tests/test_smoke.py", render("test_smoke.py.j2", empty())?);

        project.notes.push(
            "run the API with `uv sync && uv run uvicorn app.main:app`, \
             or `docker compose up` for the full stack"
                .to_owned(),
        );
        if !ctx.workers.is_empty() || !ctx.consumers.is_empty() {
            project
                .notes
                .push("start workers with `uv run python -m app.workers`".to_owned());
        }
        Ok(project)
    }
}
