#!/usr/bin/env bash
# `31UpdatePlan.md` M6: standalone callgrind instruction-count
# investigation tool, matching `scripts/bench-codegen.sh`'s own role
# for wall-clock timing -- a human-runnable, fast, narrower-scoped
# sibling to the actual gate. The gate itself
# (`tests/tests/perf_baseline.rs`) measures independently rather than
# shelling out to this script, mirroring the existing
# `bench-codegen.sh`/`tests/tests/perf_budget.rs` relationship: a
# script for people, a `#[test]` for CI, both measuring the same thing
# through separate, independently-correct code paths.
#
# Usage:
#   scripts/bench-callgrind.sh [--examples ping,order-system] [--target python]
#
# Requires valgrind on PATH. Exits non-zero only if a build or
# valgrind invocation itself fails -- this is a measuring instrument,
# not a gate (the gate is `31UpdatePlan.md` M6's own
# `tests/tests/perf_baseline.rs`).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

EXAMPLES="ping,order-system"
TARGET="python"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --examples)
            EXAMPLES="$2"
            shift 2
            ;;
        --target)
            TARGET="$2"
            shift 2
            ;;
        *)
            echo "unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

if ! command -v valgrind >/dev/null 2>&1; then
    echo "valgrind not found on PATH -- required to measure instruction counts" >&2
    exit 1
fi

echo "building ciac (release, for stable instruction counts)..." >&2
cargo build -q --release -p ciac
CIAC="$(pwd)/target/release/ciac"

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

IFS=',' read -ra EXAMPLE_LIST <<<"$EXAMPLES"

echo ""
echo "## Callgrind instruction counts: target=$TARGET"
echo ""
echo "| Example | Instructions |"
echo "|---|---|"
for name in "${EXAMPLE_LIST[@]}"; do
    example="examples/${name}.ciac"
    [[ -f "$example" ]] || { echo "missing: $example" >&2; exit 1; }
    out="$WORKDIR/${name}"
    cg_out="$WORKDIR/${name}.callgrind"
    rm -rf "$out"
    valgrind --tool=callgrind --callgrind-out-file="$cg_out" --cache-sim=no -q \
        "$CIAC" build "$example" --target "$TARGET" --out "$out" >"$WORKDIR/log" 2>&1
    instructions=$(grep "^summary:" "$cg_out" | awk '{print $2}')
    printf '| %s | %s |\n' "$name" "$instructions"
    rm -rf "$out" "$cg_out"
done

echo ""
echo "Compare against the committed \`docs/perf/baseline.json\`'s own"
echo "\`instruction_counts\` field by hand, or run the real gate:"
echo ""
echo '```sh'
echo "cargo test -p ciac-integration-tests --test perf_baseline -- --ignored"
echo '```'
echo ""
echo "To refresh the committed baseline's instruction counts (requires a"
echo "justification in the commit message, per 31UpdatePlan.md's own"
echo "discipline):"
echo ""
echo '```sh'
echo "cargo run --release -p ciac-integration-tests --bin ciac-bench -- --update-baseline --with-callgrind"
echo '```'
echo ""
echo "(generated by scripts/bench-callgrind.sh; examples=$EXAMPLES target=$TARGET; $(date -u +%Y-%m-%dT%H:%M:%SZ))"
